// src/react/pages/audit/LoginFailureLogPage.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import {
  Box,
  Button,
  ButtonGroup,
  CircularProgress,
  Stack,
  TextField,
} from "@mui/material";
import { RefreshOutlined, SearchOutlined } from "@mui/icons-material";
import type { ColDef } from "ag-grid-community";
import { PageableGridContent } from "@/react/components/ag-grid";
import type { PageableGridContentHandle } from "@/react/components/ag-grid/types";
import { LoginFailuresDataSource } from "@/react/pages/audit/LoginFailuresDataSource";
import type { LoginFailureEvent } from "@/react/pages/audit/loginFailuresApi";
import { PageToolbar } from "@/react/components/page/PageToolbar";

export function LoginFailureLogPage() {
  const gridRef = useRef<PageableGridContentHandle<LoginFailureEvent>>(null);
  const [searching, setSearching] = useState(false);
  const dataSource = useMemo(() => new LoginFailuresDataSource(setSearching), []);
  const [dateStart, setDateStart] = useState("");
  const [dateEnd, setDateEnd] = useState("");
  const [usernameLike, setUsernameLike] = useState("");

  const columnDefs = useMemo<ColDef<LoginFailureEvent>[]>(
    () => [
      { field: "id", headerName: "ID", sortable: true, flex: 0.5, filter: false },
      { field: "username", headerName: "사용자명", sortable: true, flex: 1, filter: false },
      { field: "remoteIp", headerName: "IP 주소", sortable: true, flex: 1, filter: false },
      { field: "failureType", headerName: "예외 유형", sortable: true, flex: 1.25, filter: false },
      { field: "message", headerName: "메시지", sortable: true, flex: 1.75, filter: false },
      { field: "userAgent", headerName: "User-Agent", sortable: true, flex: 2.5, filter: false },
      {
        field: "occurredAt",
        headerName: "시각",
        sortable: true,
        flex: 1.5,
        filter: false,
        valueFormatter: (params) =>
          params.value ? new Date(params.value).toLocaleString() : "",
      },
    ],
    []
  );

  const handleRefresh = () => {
    gridRef.current?.refresh();
  };

  function setPreset(days: number) {
    const now = new Date();
    const end = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const start = new Date(end);
    start.setDate(start.getDate() - (days - 1));
    setDateStart(start.toISOString().slice(0, 10));
    setDateEnd(end.toISOString().slice(0, 10));
  }

  function setToday() {
    setPreset(1);
  }

  function set7days() {
    setPreset(7);
  }

  function set30days() {
    setPreset(30);
  }

  function set6Months() {
    const now = new Date();
    const start = new Date(now.getFullYear(), now.getMonth() - 6, now.getDate());
    const end = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    setDateStart(start.toISOString().slice(0, 10));
    setDateEnd(end.toISOString().slice(0, 10));
  }

  function setThisMonth() {
    const now = new Date();
    const start = new Date(now.getFullYear(), now.getMonth(), 1);
    const end = new Date(now.getFullYear(), now.getMonth() + 1, 0);
    setDateStart(start.toISOString().slice(0, 10));
    setDateEnd(end.toISOString().slice(0, 10));
  }

  function startOfDayLocalToIso(dateStr: string) {
    const [y = 0, m = 1, d = 1] = dateStr.split("-").map(Number);
    return new Date(y, m - 1, d, 0, 0, 0, 0).toISOString();
  }

  function endOfDayExclusiveLocalToIso(dateStr: string) {
    const [y = 0, m = 1, d = 1] = dateStr.split("-").map(Number);
    return new Date(y, m - 1, d + 1, 0, 0, 0, 0).toISOString();
  }

  const validRange = !dateStart || !dateEnd || dateStart <= dateEnd;

  const handleSearch = () => {
    if (!validRange) {
      return;
    }

    const filter: Record<string, string> = {};
    if (dateStart) {
      filter.from = startOfDayLocalToIso(dateStart);
    }
    if (dateEnd) {
      filter.to = endOfDayExclusiveLocalToIso(dateEnd);
    }
    if (usernameLike.trim()) {
      filter.usernameLike = usernameLike.trim();
    }
    dataSource.applyFilter(filter);
    gridRef.current?.refresh();
  };

  useEffect(() => {
    setPreset(7);
  }, []);

  return (
    <Stack spacing={0.5}>
      <PageToolbar
        breadcrumbs={["시스템관리", "감사", "로그인 실패"]}
        label="로그인 실패 이력을 기간과 아이디 조건으로 조회합니다."
        onRefresh={handleRefresh}
        divider={false}
      />

      <Stack spacing={1}>
        <Box
          sx={{
            border: 1,
            borderColor: "divider",
            borderRadius: 1,
            px: 1,
            py: 1,
          }}
        >
          <Stack spacing={1}>
            <Stack direction={{ xs: "column", md: "row" }} spacing={1}>
              <TextField
                label="시작일(포함)"
                type="date"
                size="small"
                value={dateStart}
                onChange={(event) => setDateStart(event.target.value)}
                InputLabelProps={{ shrink: true }}
                error={!validRange}
                fullWidth
              />
              <TextField
                label="종료일(포함)"
                type="date"
                size="small"
                value={dateEnd}
                onChange={(event) => setDateEnd(event.target.value)}
                InputLabelProps={{ shrink: true }}
                error={!validRange}
                helperText={!validRange ? "시작일이 종료일보다 늦을 수 없습니다." : undefined}
                fullWidth
              />
              <TextField
                label="아이디"
                size="small"
                value={usernameLike}
                onChange={(event) => setUsernameLike(event.target.value)}
                onKeyDown={(event) => {
                  if (event.key === "Enter") {
                    handleSearch();
                  }
                }}
                fullWidth
              />
            </Stack>
            <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 1 }}>
              <ButtonGroup size="small" variant="text">
                <Button onClick={setToday}>오늘</Button>
                <Button onClick={set7days}>7일</Button>
                <Button onClick={set30days}>30일</Button>
                <Button onClick={set6Months}>6개월</Button>
                <Button onClick={setThisMonth}>이번달</Button>
              </ButtonGroup>
              <Button
                variant="outlined"
                startIcon={searching ? <CircularProgress size={16} /> : <SearchOutlined />}
                onClick={handleSearch}
                disabled={!validRange || searching}
              >
                {searching ? "조회 중..." : "조회"}
              </Button>
            </Box>
          </Stack>
        </Box>
      </Stack>

      <PageableGridContent<LoginFailureEvent>
        ref={gridRef}
        datasource={dataSource}
        columns={columnDefs}
      />
    </Stack>
  );
}

// src/views/mgmt/audit/LoginFailureLogPage.vue
<template>
    <v-breadcrumbs class="pa-0" :items="['시스템관리', '감사', '로그인 실패']" density="compact"></v-breadcrumbs>
    <PageToolbar @refresh="refresh" :closeable="false" :divider="false" :prepend-items="[
    ]" :items="[
        { icon: 'mdi-refresh', event: 'refresh', }]"></PageToolbar>
    <v-card class="mb-2" rounded="lg">
        <v-card-text class="pb-0">
            <v-row>
                <v-col>
                    <v-menu v-model="dateMenuStart" :close-on-content-click="false" transition="scale-transition"
                        offset-y>
                        <template #activator="{ props }">
                            <v-text-field v-bind="props" label="시작일(포함)" prepend-inner-icon="mdi-calendar"
                                variant="outlined" density="compact" readonly class="mr-2"
                                :model-value="dateStartDisplay" placeholder="예: 2025년 10월 29일 (수)"
                                :error="!validRange" />
                        </template>
                        <v-date-picker v-model="dateStart" @update:modelValue="dateMenuStart = false"
                            show-adjacent-months :first-day-of-week="0" />
                    </v-menu>
                    <v-menu v-model="dateMenuEnd" :close-on-content-click="false" transition="scale-transition"
                        offset-y>
                        <template #activator="{ props }">
                            <v-text-field v-bind="props" label="종료일(포함)" prepend-inner-icon="mdi-calendar"
                                variant="outlined" density="compact" readonly class="mr-2" :model-value="dateEndDisplay"
                                placeholder="예: 2025년 10월 29일 (수)" :error="!validRange"
                                :messages="!validRange ? ['시작일이 종료일보다 늦을 수 없습니다.'] : []" />
                        </template>
                        <v-date-picker v-model="dateEnd" @update:modelValue="dateMenuEnd = false" show-adjacent-months
                            :first-day-of-week="0" />
                    </v-menu>
                    <v-btn variant="tonal" class="mr-1" @click="setToday">오늘</v-btn>
                    <v-btn variant="tonal" class="mr-1" @click="set7days">7일</v-btn>
                    <v-btn variant="tonal" class="mr-1" @click="set30days">30일</v-btn>
                    <v-btn variant="tonal" class="mr-1" @click="set6Months">6개월</v-btn>
                    <v-btn variant="tonal" class="mr-1" @click="setThisMonth">이번달</v-btn>
                </v-col>
                <v-col>
                    <v-text-field clearable variant="outlined" label="아이디" density="compact"
                        v-model="usernameLike"></v-text-field>
                </v-col>
            </v-row>
        </v-card-text>
        <v-card-actions>
            <v-spacer></v-spacer>
            <v-btn class="pr-5" width="100" variant="outlined" rounded="xl" prepend-icon="mdi-magnify" text="조회"
                :disabled="!validRange" @click="onSearchClick">
            </v-btn>
        </v-card-actions>
    </v-card>
    <v-row>
        <v-col cols="12" md="12">
            <PageableGridContent @filter-actived="onPageableGridFilterActived" ref="pageableGridContentRef"
                :datasource="dataStore" :columns="columnDefs">
            </PageableGridContent>
        </v-col>
    </v-row>
</template>
<script setup lang="ts">
import GridContent from '@/components/ag-grid/GridContent.vue';
import PageableGridContent from '@/components/ag-grid/PageableGridContent.vue';
import PageToolbar from '@/components/buttons/PageToolbar.vue';
import { useConfirm } from '@/plugins/confirm';
import { useToast } from '@/plugins/toast';
import { usePageableLoginFailureLogStore } from '@/stores/studio/audit.login-failure-log.store';
import type { ColDef } from 'ag-grid-community';
import { computed, onMounted, ref, watch } from 'vue';
import { useRouter } from 'vue-router';

// grid 
const dataStore = usePageableLoginFailureLogStore();
const gridData = ref<any[]>();
const loader = ref(false);
const router = useRouter();
const confirm = useConfirm();
const toast = useToast();
const columnActions = [
    {
        label: '삭제',
        variant: 'outlined',
        prependIcon: 'mdi-delete',
        color: 'red',
        event: 'delete',
        visible: true,
        tooltip: '롤을 삭제합니다.'
    },
    {
        label: '사용자',
        color: 'blue',
        variant: 'outlined',
        prependIcon: 'mdi-account-multiple',
        event: 'user',
        visible: true,
        tooltip: '롤이 부여된 사용자를 관리합니다.',
        disabled: false,
    },
    {
        label: '그룹',
        color: 'blue',
        variant: 'outlined',
        prependIcon: 'mdi-account-group',
        event: 'group',
        visible: true,
        tooltip: '롤이 부여된 그룹을 관리합니다.',
        disabled: false,
    },
    {
        label: '상세보기',
        icon: 'mdi-chevron-right',
        event: 'view',
        visible: true,
        disabled: false,
    }
];

// define grid columns
const columnDefs: ColDef[] = [
    { field: 'id', headerName: '이름', filter: false, sortable: true, type: "number", flex: .25 },
    { field: 'occurredAt', headerName: '일시', filter: false, sortable: true, type: 'datetime', flex: .6 },
    { field: 'username', headerName: '아이디', filter: false, sortable: true, type: 'string', flex: .25 },
    { field: 'remoteIp', headerName: 'IP', filter: false, sortable: true, type: 'string', flex: .5 },
    { field: 'message', headerName: '메시지', filter: false, sortable: false, type: 'string', flex: 1 },
    { field: 'userAgent', headerName: 'UserAgent', filter: false, sortable: false, type: 'string', },
];

const gridContentRef = ref<InstanceType<typeof GridContent> | null>(null);
const pageableGridContentRef = ref<InstanceType<typeof PageableGridContent> | null>(null);
const filtersActive = ref(false);

function onPageableGridFilterActived(event: any) {
    filtersActive.value = event;
}
const refresh = () => {
    pageableGridContentRef.value?.refresh();
}
const onClearFilters = () => {
    pageableGridContentRef.value?.clearFilters();
};

const selectedRows = computed(() => pageableGridContentRef.value?.selectedRows() || []);

const fmtKo = new Intl.DateTimeFormat('ko-KR', {
    year: 'numeric', month: 'long', day: 'numeric',
    weekday: 'short', timeZone: 'Asia/Seoul',
});
const dateStartDisplay = computed(() => dateStart.value ? fmtKo.format(new Date(dateStart.value)) : '');
const dateEndDisplay = computed(() => dateEnd.value ? fmtKo.format(new Date(dateEnd.value)) : '');

const dateStart = ref<string | null>(null) // 'YYYY-MM-DD'
const dateEnd = ref<string | null>(null) // 'YYYY-MM-DD'
const dateMenuStart = ref(false)
const dateMenuEnd = ref(false)

// v-data-table-server 모델
const page = ref(1)       // v-data-table는 1-based
const itemsPerPage = ref(15)
const sortBy = ref<{ key: string, order: 'asc' | 'desc' }[]>([
    { key: 'occurredAt', order: 'desc' }
])

// ====== 유틸: 로컬 날짜를 ISO(UTC)로 변환 ======
/**
 * YYYY-MM-DD -> 로컬타임 기준 00:00의 ISO UTC
 */
function startOfDayLocalToIso(dateStr: string): string {
    const [y, m, d] = dateStr.split('-').map(Number)
    const dt = new Date(y, m - 1, d, 0, 0, 0, 0) // local
    return dt.toISOString()
}
/**
 * YYYY-MM-DD -> 로컬타임 기준 다음날 00:00의 ISO UTC (end-exclusive)
 */
function endOfDayExclusiveLocalToIso(dateStr: string): string {
    const [y, m, d] = dateStr.split('-').map(Number)
    const dt = new Date(y, m - 1, d + 1, 0, 0, 0, 0) // 다음날 00:00
    return dt.toISOString()
}

const validRange = computed(() => {
    if (!dateStart.value || !dateEnd.value) return true
    return dateStart.value <= dateEnd.value
})

const queryFrom = computed(() => {
    if (!dateStart.value) return null
    return startOfDayLocalToIso(dateStart.value)
})
const queryTo = computed(() => {
    if (!dateEnd.value) return null
    return endOfDayExclusiveLocalToIso(dateEnd.value)
})


// 초기: 최근 7일
function setPreset(days: number) {
    const now = new Date()
    const end = new Date(now.getFullYear(), now.getMonth(), now.getDate()) // today
    const start = new Date(end)
    start.setDate(start.getDate() - (days - 1))
    dateStart.value = start.toISOString().slice(0, 10)
    dateEnd.value = end.toISOString().slice(0, 10)
}

// ====== 빠른 범위 ======
function setToday() { setPreset(1) }
function set7days() { setPreset(7) }
function set30days() { setPreset(30) }
function setThisMonth() {
    const now = new Date();
    const start = new Date(now.getFullYear(), now.getMonth(), 1)
    const end = new Date(now.getFullYear(), now.getMonth() + 1, 0)
    dateStart.value = start.toISOString().slice(0, 10)
    dateEnd.value = end.toISOString().slice(0, 10)
}

function set6Months() {
    const now = new Date()
    const start = new Date(now.getFullYear(), now.getMonth() - 6, now.getDate())
    const end = new Date(now.getFullYear(), now.getMonth(), now.getDate())
    dateStart.value = start.toISOString().slice(0, 10)
    dateEnd.value = end.toISOString().slice(0, 10)
}


const usernameLike = ref<string>();
// 수동 조회 버튼
function onSearchClick() {
    if (!validRange.value) return
    fetchPage();
}

async function fetchPage() {
    const params: Record<string, any> = {}
    if (queryFrom.value) params.from = queryFrom.value
    if (queryTo.value) params.to = queryTo.value
    if (usernameLike.value) params.usernameLike = usernameLike.value
    dataStore.setFilter(params);
    refresh();
}

onMounted(() => {
    setPreset(7)
});

</script>
