// src/react/pages/mail/MailSyncPage.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import { Alert, IconButton, Stack, Tooltip } from "@mui/material";
import { EmailOutlined } from "@mui/icons-material";
import type { ColDef } from "ag-grid-community";
import { PageableGridContent } from "@/react/components/ag-grid";
import type { PageableGridContentHandle } from "@/react/components/ag-grid/types";
import { reactMailApi } from "@/react/pages/mail/api";
import { MailSyncLogDataSource } from "@/react/pages/mail/datasource";
import { toast } from "@/react/feedback";
import type { MailSyncLogDto } from "@/types/studio/mail";
import { resolveAxiosError } from "@/utils/helpers";
import { PageToolbar } from "@/react/components/page/PageToolbar";

export function MailSyncPage() {
  const gridRef = useRef<PageableGridContentHandle<MailSyncLogDto>>(null);
  const dataSource = useMemo(() => new MailSyncLogDataSource(), []);
  const [error, setError] = useState<string | null>(null);
  const [syncing, setSyncing] = useState(false);

  const columnDefs = useMemo<ColDef<MailSyncLogDto>[]>(
    () => [
      { field: "logId", headerName: "ID", flex: 0.25, sortable: true },
      { field: "processed", headerName: "처리건수", flex: 0.3, sortable: true },
      { field: "succeeded", headerName: "성공건수", flex: 0.3, sortable: true },
      { field: "failed", headerName: "실패건수", flex: 0.3, sortable: true },
      {
        field: "startedAt",
        headerName: "시작일",
        flex: 0.55,
        sortable: true,
        type: "datetime",
      },
      {
        field: "finishedAt",
        headerName: "종료일",
        flex: 0.55,
        sortable: true,
        type: "datetime",
      },
      { field: "status", headerName: "상태", flex: 0.3, sortable: true },
      { field: "message", headerName: "메시지", flex: 1 },
      { field: "triggeredBy", headerName: "방법", flex: 0.45 },
    ],
    []
  );

  useEffect(() => {
    const unsubscribe = reactMailApi.subscribeSync(
      (payload) => {
        if (payload.status === "completed") {
          toast.success(`메일 동기화 완료 (#${payload.logId})`);
          gridRef.current?.refresh();
          setSyncing(false);
        } else if (payload.status === "failed") {
          toast.error(payload.message || `메일 동기화 실패 (#${payload.logId})`);
          gridRef.current?.refresh();
          setSyncing(false);
        }
      },
      () => {
        setError("메일 동기화 SSE 연결에 실패했습니다.");
        setSyncing(false);
      }
    );

    return () => {
      unsubscribe();
    };
  }, []);

  async function handleSync() {
    setError(null);
    setSyncing(true);
    try {
      await reactMailApi.startSync();
      toast.info("메일 동기화를 요청했습니다.");
      gridRef.current?.refresh();
    } catch (syncError) {
      const message = resolveAxiosError(syncError);
      setError(message);
      toast.error(message);
    } finally {
      setSyncing(false);
    }
  }

  return (
    <Stack spacing={0.5}>
      <PageToolbar
        divider={false}
        breadcrumbs={["애플리케이션", "메일", "Sync"]}
        label="메일 동기화를 요청하고 처리 로그를 확인합니다."
        onRefresh={() => gridRef.current?.refresh()}
        actions={
          <Tooltip title="메일 동기화를 요청합니다.">
            <span>
              <IconButton size="small" onClick={() => void handleSync()} disabled={syncing}>
                <EmailOutlined fontSize="small" />
              </IconButton>
            </span>
          </Tooltip>
        }
      />
      {error ? <Alert severity="error">{error}</Alert> : null}

      <PageableGridContent<MailSyncLogDto>
        ref={gridRef}
        datasource={dataSource}
        columns={columnDefs}
      />
    </Stack>
  );
}

// src/views/studio/mgmt/application/mail/MailSyncPage.vue
<template>
    <v-breadcrumbs class="pa-0" :items="['응용프로그램', '메일', '메일 동기화']" density="compact"></v-breadcrumbs>
    <PageToolbar @refresh="refresh" @email-sync="email_sync" :closeable="false" :divider="true"
        :prepend-items="[
        ]" :items="[
            { icon: 'mdi-email-sync', event: 'email-sync', color: 'blue', tooltip: '메일 동기화 요청' },
            { icon: 'mdi-refresh', event: 'refresh', tooltip: '새로고침' }

        ]"></PageToolbar>
    <PageableGridContent class="mt-1" @filter-actived="onPageableGridFilterActived" ref="pageableGridContentRef"
        :datasource="dataStore" :columns="columnDefs">
    </PageableGridContent>
    <v-overlay v-model="overlay" contained class="align-center justify-center">
        <v-progress-circular color="primary" indeterminate size="64" />
    </v-overlay>
</template>
<script setup lang="ts">
import PageableGridContent from '@/components/ag-grid/PageableGridContent.vue';
import PageToolbar from '@/components/bars/PageToolbar.vue';
import { mailSync } from '@/data/studio/mgmt/mail';
import { useConfirm } from '@/plugins/confirm';
import { useToast } from '@/plugins/toast';
import { usePageableMailSyncLogStore } from '@/stores/studio/mgmt/mail.synclog.store';
import { useMailSyncRealtimeStore } from '@/stores/studio/mgmt/mail.sync.realtime.store';
import { resolveAxiosError } from '@/utils/helpers';
import type { ColDef } from 'ag-grid-community';
import { ref, watch } from 'vue';
import ContentCellRender from '../../services/ai/ContentCellRender.vue';

const confirm = useConfirm();
const toast = useToast();
const overlay = ref<boolean>(false);
const mailSyncRealtime = useMailSyncRealtimeStore();

// grid 
const dataStore = usePageableMailSyncLogStore();
const columnDefs: ColDef[] = [
    { field: 'logId', headerName: 'ID', filter: false, type: 'number', flex: .25, },
    { field: 'processed', headerName: '처리건수', filter: false, type: "number", flex: .25 },
    { field: 'succeeded', headerName: '성공건수', filter: false, type: "number", flex: .25 },
    { field: 'failed', headerName: '실패건수', filter: false, type: "number", flex: .25 },
    { field: 'startedAt', headerName: '시작일', filter: false, type: 'datetime', flex: .5 },
    { field: 'finishedAt', headerName: '종료일', filter: false, type: 'datetime', flex: .5 },
    { field: 'status', headerName: '상태', filter: false, type: 'text', flex: .25 },
    { field: 'message', headerName: '메시지', tooltipField: "message", filter: false, sortable: false, type: 'text', cellRenderer: ContentCellRender, flex: 1 },
    { field: 'triggeredBy', headerName: '방법', filter: false, type: 'text', flex: .5 },
];
const pageableGridContentRef = ref<InstanceType<typeof PageableGridContent> | null>(null);
const filtersActive = ref(false);
function onPageableGridFilterActived(event: any) {
    filtersActive.value = event;
}

const refresh = () => {
    pageableGridContentRef.value?.refresh();
}

const email_sync = async () => {
    const ok = await confirm({
        title: '확인',
        message: `메일 데이터를 가져오겠습니까? 이 작업은 되돌릴 수 없습니다.`,
        okText: '네',
        cancelText: '아니오',
        color: 'primary',
    });
    if (!ok) return;
    try {
        overlay.value = true;
        await mailSync();
        // 전역 실시간 알림에서 완료/실패 메시지를 표시합니다.
    } catch (e: any) {
        toast.error(resolveAxiosError(e));
    } finally {
        overlay.value = false;
    }
}

watch(() => mailSyncRealtime.lastEvent, (payload) => {
    if (!payload) return;
    if (payload.status === "completed") {
        refresh();
    }
});

</script>
