// src/views/studio/mgmt/services/ai/RagPage.vue
<template>
    <v-breadcrumbs class="pa-0" :items="['서비스 관리', 'AI', 'RAG']" density="compact"></v-breadcrumbs>
    <PageToolbar title="검색" label="문서 벡터를 검색합니다." @refresh="refresh" :closeable="false" :divider="true" :prepend-items="[
    ]" :items="[
        { icon: 'mdi-refresh', event: 'refresh', }]"></PageToolbar>
    <v-card density="compact" class="mt-5">
        <v-alert closable rounded="0" icon="mdi-tooltip"
            :text="`질문을 벡터로 변환해 전체 문서 벡터와 비교하고, 그중 가장 비슷한 상위 ${searchForm.topK}개(Top-${searchForm.topK})를 찾아 결과를 보여줍니다.`"
            type="info" max-height="100"></v-alert>
        <v-card-text class="pb-0">
            <v-container fluid class="pa-0">
                <v-row>
                    <v-col cols="2">
                        <v-number-input v-model="searchForm.topK" :reverse="false" controlVariant="default" label="topK" density="compact"
                            hide-details :hideInput="false" :min="0" :inset="false"></v-number-input>
                    </v-col>
                    <v-col>
                        <v-text-field v-model="searchForm.query" label="쿼리" placeholder="쿼리(질문)을 입력하세요." row-height="15" density="compact"
                            rows="2" hide-details>
                            <template v-slot:append>
                                <v-btn icon="mdi-text-search" variant="tonal" @click="searchSemantic(false)"></v-btn>
                            </template>
                        </v-text-field>
                    </v-col>
                </v-row>
                <v-row>
                    <v-col>
                        <v-checkbox v-model="useQueryRewrite" :label="queryRewriteLabel"
                            hint="입력한 검색어를 AI가 관련 키워드로 확장해 더 다양한 결과를 찾습니다."></v-checkbox>
                    </v-col>
                </v-row>
            </v-container>
        </v-card-text>
        <v-expand-transition v-show="useQueryRewrite">
            <v-container fluid>
                <v-row>
                    <v-col>
                        <v-select prepend-icon="mdi-robot-outline" v-model="provider" :items="providerNames"
                            hide-details label="Provider" placeholder="provider (옵션)" variant="underlined" density="compact"
                            @update:model-value="onProviderChange" />
                    </v-col>
                    <v-col>
                        <v-text-field v-model="model" color="primary" label="LLM Model" placeholder="model (옵션)" density="compact"
                            hide-details variant="underlined"></v-text-field>
                    </v-col>
                    <v-col>
                        <v-btn :disabled="!enabledQueryRewrite" variant="outlined"
                            prepend-icon="mdi-file-replace-outline" rounded="xl" color="red" hide-details width="120" 
                            @click="queryRewrite" :loading="queryRewriting">
                            쿼리 확장
                        </v-btn>
                    </v-col>
                </v-row>
                <v-row v-if="expandedKeywords.length>0">
                    <v-col>
                        <v-chip-group selected-class="text-primary" column>
                            <v-chip v-for="tag in expandedKeywords" :key="tag">
                                {{ tag }}
                            </v-chip>
                        </v-chip-group>
                    </v-col>
                </v-row>
                <v-row>
                    <v-col>
                        <v-text-field v-model="expandedQuery" label="확장 쿼리" placeholder="화장쿼리는 자동 생생됩니다." density="compact"
                            row-height="15" max-rows="3" auto-grow readonly rows="2" hide-details>
                            <template v-slot:append>
                                <v-btn icon="mdi-text-search" variant="tonal" @click="searchSemantic(true)"></v-btn>
                            </template>
                        </v-text-field></v-col>
                </v-row>
            </v-container>
        </v-expand-transition>
    </v-card>
    <v-row>
        <v-col cols="12" md="12">
            <GridContent ref="gridContentRef" :rowData="gridData" style="" :options="{ rowHeight: 60 }"
                :auto-resize="false" :columns="columnDefs" class="mt-5">
            </GridContent>
        </v-col>
    </v-row>
</template>
<script setup lang="ts">
import GridContent from '@/components/ag-grid/GridContent.vue';
import PageToolbar from '@/components/bars/PageToolbar.vue';
import { fetchProviders, rewriteQuery, searchVector } from '@/data/studio/public/ai';
import { useToast } from '@/plugins/toast';
import type { AiInfoResponse, ProviderInfo, QueryRewriteRequestDto, VectorSearchRequestDto, VectorSearchResultDto } from '@/types/studio/ai';
import { resolveAxiosError } from '@/utils/helpers';
import type { ColDef } from 'ag-grid-community';
import { computed, onMounted, reactive, ref } from 'vue';
import ContentCellRender from './ContentCellRender.vue';
import MetadataCellRender from './MetadataCellRender.vue';

const toast = useToast();

type SearchFormState = {
    query: string;
    embedding: string;
    topK: number | null;
};

const searchForm = reactive<SearchFormState>({
    query: '',
    embedding: '',
    topK: 3
});


const gridData = ref<VectorSearchResultDto[]>([]);
const loader = ref(false);
// define grid columns
const columnDefs: ColDef[] = [
    { field: 'documentId', headerName: 'ID', filter: false, sortable: true, type: "number", maxWidth: 100 },
    {
        field: 'score', headerName: '유사도', filter: false, sortable: true, type: "string", maxWidth: 100, valueFormatter: (params) => {
            if (!params.value) return "";
            return (params.value * 100).toFixed(2)
        },
    },
    { field: 'content', tooltipField: "content", headerName: '콘텐츠', filter: false, sortable: true, type: 'text', flex: 1, cellRenderer: ContentCellRender },
    {
        field: 'metadata', tooltipField: "content", headerName: '메타정보', filter: false, sortable: true, type: 'text', flex: 1,
        cellRenderer: MetadataCellRender
    },
];

const gridContentRef = ref<InstanceType<typeof GridContent> | null>(null);

async function searchSemantic(usingExpandedQuery: boolean = false) {
    loader.value = true;
    try {
        const payload = buildSearchPayload(searchForm);
        if( usingExpandedQuery )
            payload.query = expandedQuery.value;

        const data = await searchVector(payload);
        gridData.value = data;
    } catch (e: any) {
        toast.error(resolveAxiosError(e));
    } finally {
        gridContentRef.value?.loading(false);
        loader.value = false;
    }
}

const buildSearchPayload = (form: SearchFormState): VectorSearchRequestDto => {
    return {
        query: form.query || null,
        topK: Number(form.topK) || 3,
        hybrid: true,
    };
};

const refresh = () => {

}
const enabledQueryRewrite = computed(() => searchForm.query.length > 1 ? true : false);
const queryRewriting = ref<boolean>(false);
const useQueryRewrite = ref<boolean>(false);
const queryRewriteLabel = computed(() =>
    useQueryRewrite.value ? '검색어 자동 확장 : 활성화' : '검색어 자동 확장 : 비활성화'
);
const expandedQuery = ref<string>();
const expandedKeywords = ref<string[]>([]);
async function queryRewrite() {

    queryRewriting.value = true;
    try {
        const req: QueryRewriteRequestDto = {
            query: searchForm.query
        }
        const data = await rewriteQuery(req);
        expandedQuery.value = data.expandedQuery;
        expandedKeywords.value = data.keywords;
    } catch (e: any) {
        toast.error(resolveAxiosError(e));
    } finally {
        queryRewriting.value = false;
    }

}

/** query rewrite ...  */
const aiInfo = ref<AiInfoResponse | null>(null);
const providers = computed<ProviderInfo[]>(() => aiInfo.value?.providers ?? []);
const providerNames = computed<string[]>(
    () => aiInfo.value?.providers?.map(p => p.name) ?? []
);
const provider = ref("google-ai-gemini");
const model = ref("gemini-2.0-flash"); // 필요시 기본값 교체

function getChatModel(name?: string | null): string | null {
    return findProvider(name)?.chat?.model ?? null;
}
function findProvider(name?: string | null): ProviderInfo | undefined {
    const key = (name ?? aiInfo.value?.defaultProvider ?? "").toLowerCase();
    return providers.value.find(p => p.name.toLowerCase() === key);
}

function setChatModel(name?: string | null): void {
    const chatModel = getChatModel(name);
    if (chatModel)
        model.value = chatModel;
    else
        model.value = "";
}

const onProviderChange = (val: string | null) => {
    if (val)
        setChatModel(val);
}

async function getData() {

    try {
        const data = await fetchProviders(false);
        aiInfo.value = data;
        if (aiInfo.value)
            provider.value = aiInfo.value.defaultProvider;
        setChatModel(provider.value);
    } catch (e: any) {
        toast.error(resolveAxiosError(e));
    }

}

onMounted(() => {
    getData();
});


</script>

// src/react/pages/ai/RagPage.tsx
import { useEffect, useMemo, useState } from "react";
import {
  Alert,
  Breadcrumbs,
  Button,
  Card,
  CardContent,
  Chip,
  MenuItem,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import type { ColDef } from "ag-grid-community";
import { GridContent } from "@/react/components/ag-grid";
import { reactAiApi } from "@/react/pages/ai/api";
import type {
  AiInfoResponse,
  ChatMessageDto,
  ProviderInfo,
  VectorSearchResultDto,
} from "@/types/studio/ai";
import { resolveAxiosError } from "@/utils/helpers";

export function RagPage() {
  const [aiInfo, setAiInfo] = useState<AiInfoResponse | null>(null);
  const [provider, setProvider] = useState("");
  const [model, setModel] = useState("");
  const [query, setQuery] = useState("");
  const [topK, setTopK] = useState("3");
  const [expandedQuery, setExpandedQuery] = useState("");
  const [expandedKeywords, setExpandedKeywords] = useState<string[]>([]);
  const [rows, setRows] = useState<VectorSearchResultDto[]>([]);
  const [chatInput, setChatInput] = useState("");
  const [chatMessages, setChatMessages] = useState<ChatMessageDto[]>([]);
  const [error, setError] = useState<string | null>(null);

  const providers = useMemo<ProviderInfo[]>(() => aiInfo?.providers ?? [], [aiInfo]);

  useEffect(() => {
    reactAiApi
      .fetchProviders()
      .then((data) => {
        setAiInfo(data);
        setProvider(data.defaultProvider);
        const match = data.providers.find((item) => item.name === data.defaultProvider);
        setModel(match?.chat.model ?? "");
      })
      .catch((loadError) => setError(resolveAxiosError(loadError)));
  }, []);

  const columnDefs = useMemo<ColDef<VectorSearchResultDto>[]>(
    () => [
      { field: "id", headerName: "ID", flex: 0.5 },
      { field: "score", headerName: "유사도", flex: 0.3, sortable: true },
      { field: "content", headerName: "콘텐츠", flex: 1.3 },
    ],
    []
  );

  async function handleSearch(usingExpandedQuery = false) {
    setError(null);
    try {
      const data = await reactAiApi.searchVector({
        query: usingExpandedQuery ? expandedQuery : query,
        topK: Number(topK) || 3,
        hybrid: true,
      });
      setRows(data);
    } catch (searchError) {
      setError(resolveAxiosError(searchError));
    }
  }

  async function handleRewrite() {
    setError(null);
    try {
      const data = await reactAiApi.rewriteQuery({ query });
      setExpandedQuery(data.expandedQuery);
      setExpandedKeywords(data.keywords);
    } catch (rewriteError) {
      setError(resolveAxiosError(rewriteError));
    }
  }

  async function handleRagChat() {
    const trimmed = chatInput.trim();
    if (!trimmed) {
      return;
    }

    const nextMessages: ChatMessageDto[] = [
      ...chatMessages,
      { role: "user", content: trimmed },
    ];

    setChatMessages(nextMessages);
    setChatInput("");
    setError(null);

    try {
      const response = await reactAiApi.sendRagChat({
        chat: {
          provider: provider || undefined,
          model: model || undefined,
          messages: nextMessages,
        },
        ragQuery: expandedQuery.trim() || query.trim() || trimmed,
        ragTopK: Number(topK) || 3,
      });

      const assistant = [...response.messages]
        .reverse()
        .find((message) => message.role === "assistant");

      if (assistant) {
        setChatMessages((current) => [...current, assistant]);
      }
    } catch (chatError) {
      setError(resolveAxiosError(chatError));
    }
  }

  return (
    <Stack spacing={2}>
      <Breadcrumbs separator="›">
        <Typography color="text.secondary">서비스 관리</Typography>
        <Typography color="text.secondary">AI</Typography>
        <Typography color="text.primary">RAG</Typography>
      </Breadcrumbs>
      <Typography variant="h5">RAG Search</Typography>
      {error ? <Alert severity="error">{error}</Alert> : null}
      <Stack direction={{ xs: "column", md: "row" }} spacing={2}>
        <TextField
          select
          label="Provider"
          value={provider}
          onChange={(event) => {
            const nextProvider = event.target.value;
            setProvider(nextProvider);
            const match = providers.find((item) => item.name === nextProvider);
            setModel(match?.chat.model ?? "");
          }}
          fullWidth
        >
          {providers.map((item) => (
            <MenuItem key={item.name} value={item.name}>
              {item.name}
            </MenuItem>
          ))}
        </TextField>
        <TextField label="Model" value={model} onChange={(event) => setModel(event.target.value)} fullWidth />
        <TextField label="topK" value={topK} onChange={(event) => setTopK(event.target.value)} sx={{ maxWidth: 140 }} />
      </Stack>
      <TextField label="쿼리" value={query} onChange={(event) => setQuery(event.target.value)} />
      <Stack direction="row" spacing={1}>
        <Button variant="contained" onClick={() => void handleSearch(false)} disabled={!query.trim()}>
          검색
        </Button>
        <Button variant="outlined" onClick={() => void handleRewrite()} disabled={!query.trim()}>
          쿼리 확장
        </Button>
        <Button variant="text" onClick={() => void handleSearch(true)} disabled={!expandedQuery.trim()}>
          확장 쿼리로 검색
        </Button>
      </Stack>
      <Card variant="outlined">
        <CardContent>
          <Stack spacing={2}>
            <Typography variant="subtitle2">RAG Chat</Typography>
            <Stack spacing={1}>
              {chatMessages.length === 0 ? (
                <Typography color="text.secondary">RAG 대화를 시작하세요.</Typography>
              ) : (
                chatMessages.map((message, index) => (
                  <TextField
                    key={`${message.role}-${index}`}
                    label={message.role}
                    value={message.content}
                    InputProps={{ readOnly: true }}
                    multiline
                    minRows={2}
                  />
                ))
              )}
            </Stack>
            <TextField
              label="RAG 질문"
              value={chatInput}
              onChange={(event) => setChatInput(event.target.value)}
              multiline
              minRows={3}
            />
            <Stack direction="row" justifyContent="flex-end">
              <Button variant="contained" onClick={() => void handleRagChat()} disabled={!chatInput.trim()}>
                RAG 요청
              </Button>
            </Stack>
          </Stack>
        </CardContent>
      </Card>
      {expandedKeywords.length > 0 ? (
        <Card variant="outlined">
          <CardContent>
            <Stack spacing={1}>
              <Typography variant="subtitle2">확장 키워드</Typography>
              <Stack direction="row" spacing={1} flexWrap="wrap">
                {expandedKeywords.map((keyword) => (
                  <Chip key={keyword} label={keyword} />
                ))}
              </Stack>
              <TextField label="확장 쿼리" value={expandedQuery} InputProps={{ readOnly: true }} />
            </Stack>
          </CardContent>
        </Card>
      ) : null}
      <GridContent<VectorSearchResultDto> columns={columnDefs} rowData={rows} height={360} />
    </Stack>
  );
}
