// src/views/studio/mgmt/application/template/TemplatesPage.vue
<template>
    <v-breadcrumbs class="pa-0" :items="['응용프로그램', '자원', '템플릿']" density="compact"></v-breadcrumbs>
    <PageToolbar title="템플릿 목록" @refresh="refresh" @create="dialogs.create.visible = true;" @delete="onDeleteSelected"
        :closeable="false" :divider="true" :prepend-items="[
    ]" :items="[
        { icon: 'mdi-file-plus', event: 'create', color: 'blue', tooltip: '새로운 템픞릿 만들기' },
        { icon: 'mdi-delete', event: 'delete', color: 'error', tooltip: '선택 삭제', disabled: isDeleteDisabled },
        { icon: 'mdi-refresh', event: 'refresh', tooltip: '새로고침' }
    ]"></PageToolbar>
    <v-card density="compact" class="mt-1" variant="text">
        <v-card-actions class="pa-0">
            <v-container fluid class="pa-0">
                <v-row>
                    <v-col cols="2">
                        <v-number-input v-model="objectType" :reverse="false" controlVariant="default" label="객체 유형"
                            :hideInput="false" hide-details variant="outlined" density="compact" :min="0"
                            :inset="false"></v-number-input>
                    </v-col>
                    <v-col cols="2">
                        <v-number-input v-model="objectId" :reverse="false" controlVariant="default" label="객체 식별자"
                            :hideInput="false" hide-details variant="outlined" density="compact" :min="0"
                            :inset="false"></v-number-input>
                    </v-col>
                    <v-col>
                        <v-text-field v-model="q" label="검색어" placeholder="파일 이름을 입력하세요."
                            @keydown.enter="onSearchClick" hide-details variant="outlined" density="compact">
                            <template v-slot:append>
                                <v-btn icon="mdi-text-search" variant="tonal"></v-btn>
                            </template>
                        </v-text-field>
                    </v-col>
                </v-row>
            </v-container>
        </v-card-actions>
    </v-card>
    <PageableGridContent ref="pageableGridContentRef" @filter-actived="onPageableGridFilterActived"
        :datasource="dataStore" :columns="columnDefs" :options="gridOptions" :events="gridEvents">
    </PageableGridContent>
    <CreateTemplateDialog v-model="dialogs.create.visible" @close="dialogs.create.visible = false"
        @complete="refresh"></CreateTemplateDialog>
</template>
<script setup lang="ts">
import PageableGridContent from '@/components/ag-grid/PageableGridContent.vue';
import PageToolbar from '@/components/bars/PageToolbar.vue';
import { useConfirm } from '@/plugins/confirm';
import { useToast } from '@/plugins/toast';
import { useNavStore } from '@/stores/studio/mgmt/nav.store';
import { usePageableTemplateStore } from '@/stores/studio/mgmt/template.store';
import type { ColDef, GridOptions, SelectionChangedEvent } from 'ag-grid-community';
import { computed, onMounted, ref } from 'vue';
import CreateTemplateDialog from './CreateTemplateDialog.vue';
import { useRouter } from 'vue-router';
import RemoteMgmtUserCellRenderer from '@/components/ag-grid/renderer/RemoteMgmtUserCellRenderer.vue';
import { deleteTemplate } from '@/data/studio/mgmt/template';
import { resolveAxiosError } from '@/utils/helpers';

const dataStore = usePageableTemplateStore();
const confirm = useConfirm();
const toast = useToast(); 
const router = useRouter();
const nav = useNavStore();
// Grid
const columnDefs: ColDef[] = [
    { field: 'templateId', headerName: 'ID', filter: false, sortable: true, type: "number", maxWidth: 80 },
    { field: 'objectType', headerName: '유형', filter: false, type: 'number', maxWidth: 80 },
    { field: 'objectId', headerName: '식별자', filter: false, type: 'number', maxWidth: 80 },
    {
        field: 'name', headerName: '이름', filter: false, sortable: true, type: "hyperlinks", flex: 2, cellRendererParams: {
            mode: 'router',
            to: (d: any) => ({ name: 'TemplateDetails', params: { templateId: d.templateId } }),
            router: router,
        }
    },
    { field: 'displayName', headerName: '한글 이름', filter: false, sortable: true, type: "string", flex: 2 },
    { field: 'createdBy', headerName: '생성자', filter: false, type: 'number', flex: 1, cellRenderer: RemoteMgmtUserCellRenderer },
    { field: 'createdAt', headerName: '생성일시', filter: false, type: 'datetime', flex: 1 },
    { field: 'updatedBy', headerName: '수정자', filter: false, cellRenderer: RemoteMgmtUserCellRenderer, flex: 1 },
    { field: 'updatedAt', headerName: '수정일시', filter: false, type: 'datetime', flex: 1 },
];
const gridOptions: GridOptions = {
    rowSelection: { mode: 'multiRow', enableClickSelection: true, checkboxes: true, headerCheckbox: false },
    selectionColumnDef: {
        width: 65,
        minWidth: 65,
        maxWidth: 65,
        pinned: 'left',
        sortable: false,
        filter: false,
        resizable: false,
    },
    rowMultiSelectWithClick: true,
};
const pageableGridContentRef = ref<InstanceType<typeof PageableGridContent> | null>(null);
const filtersActive = ref(false);
const selectedCount = ref(0);
const selectedIds = ref<number[]>([]);
const isDeleteDisabled = computed(() => selectedCount.value === 0);
const gridEvents = [
    {
        type: 'selectionChanged',
        listener: (event: SelectionChangedEvent) => {
            const rows = event.api.getSelectedRows() as Array<{ templateId?: number }>;
            selectedCount.value = rows.length;
            selectedIds.value = rows
                .map((row) => Number(row.templateId))
                .filter((id) => Number.isFinite(id) && id > 0);
        },
    },
];
function onPageableGridFilterActived(event: any) {
    filtersActive.value = event;
}
const refresh = () => {
    selectedCount.value = 0;
    selectedIds.value = [];
    pageableGridContentRef.value?.refresh();
}
const q = ref<string | null>(null)
const objectType = ref<number | null>(null)
const objectId = ref<number | null>(null)
// 수동 조회 버튼
function onSearchClick() {
    const params: Record<string, any> = {}
    if (q.value) {
        params.q = q.value
    }
    if (objectType.value != null) {
        params.objectType = objectType.value
    }
    if (objectId.value != null) {
        params.objectId = objectId.value
    }
    params.fields = "name,subject"
    dataStore.setFilter(params);
    refresh();
}

const dialogs = ref({
    create: { visible: false },
});

const onDeleteSelected = async () => {
    const ids = selectedIds.value;
    if (ids.length === 0) return;
    const ok = await confirm({
        title: '삭제 확인',
        message: `선택한 ${ids.length}개의 템플릿을 삭제하시겠습니까?`,
        okText: '삭제',
        cancelText: '취소',
        color: 'error',
    });
    if (!ok) return;
    try {
        await Promise.all(ids.map((id) => deleteTemplate(id)));
        toast.success('삭제 완료');
        pageableGridContentRef.value?.deselectAll();
        selectedCount.value = 0;
        selectedIds.value = [];
        refresh();
    } catch (e) {
        toast.error(resolveAxiosError(e));
    }
};

onMounted(async () => { 
    if( nav.previous?.name === 'TemplateDetails' && dataStore.page > 0){
        pageableGridContentRef.value?.goToPreviousPage();
    }
});

</script>

// src/react/pages/templates/TemplatesPage.tsx
import { useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  Avatar,
  Box,
  Stack,
  IconButton,
  Tooltip,
  TextField,
  Typography,
} from "@mui/material";
import { AddOutlined, DeleteOutlineOutlined } from "@mui/icons-material";
import type { ColDef, ICellRendererParams, SelectionChangedEvent } from "ag-grid-community";
import { PageableGridContent } from "@/react/components/ag-grid";
import type { PageableGridContentHandle } from "@/react/components/ag-grid/types";
import { ReactPageDataSource } from "@/react/pages/admin/datasource";
import { CreateTemplateDialog } from "@/react/pages/templates/CreateTemplateDialog";
import type { TemplateSummaryDto } from "@/types/studio/template";
import { PageToolbar } from "@/react/components/page/PageToolbar";
import { useConfirm, useToast } from "@/react/feedback";
import { reactTemplatesApi } from "@/react/pages/templates/api";

class TemplatesDataSource extends ReactPageDataSource<TemplateSummaryDto> {
  constructor() {
    super("/api/mgmt/templates");
  }
}

export function TemplatesPage() {
  const navigate = useNavigate();
  const confirm = useConfirm();
  const toast = useToast();
  const gridRef = useRef<PageableGridContentHandle<TemplateSummaryDto>>(null);
  const dataSource = useMemo(() => new TemplatesDataSource(), []);
  const [createOpen, setCreateOpen] = useState(false);
  const [keyword, setKeyword] = useState("");
  const [objectType, setObjectType] = useState("");
  const [objectId, setObjectId] = useState("");
  const [selectedIds, setSelectedIds] = useState<number[]>([]);
  const selectedCount = selectedIds.length;

  const columnDefs = useMemo<ColDef<TemplateSummaryDto>[]>(
    () => [
      { field: "templateId", headerName: "ID", type: "number", maxWidth: 90, sortable: true, filter: false },
      { field: "objectType", headerName: "유형", type: "number", maxWidth: 90, sortable: true, filter: false },
      { field: "objectId", headerName: "식별자", type: "number", maxWidth: 100, sortable: true, filter: false },
      {
        field: "name",
        headerName: "이름",
        flex: 1.5,
        sortable: true,
        filter: false,
        cellRenderer: (params: ICellRendererParams<TemplateSummaryDto>) => (
          <Box
            component="button"
            type="button"
            onClick={(event) => {
              event.stopPropagation();
              navigate(`/application/templates/${params.data?.templateId}`);
            }}
            sx={{
              border: 0,
              p: 0,
              bgcolor: "transparent",
              color: "primary.main",
              cursor: "pointer",
              font: "inherit",
              textAlign: "left",
              "&:hover": { textDecoration: "underline" },
            }}
          >
            {params.value}
          </Box>
        ),
      },
      { field: "displayName", headerName: "표시 이름", flex: 1.5, sortable: true, filter: false },
      {
        field: "createdBy",
        headerName: "생성자",
        flex: 0.75,
        sortable: true,
        filter: false,
        cellRenderer: (params: ICellRendererParams<TemplateSummaryDto>) => (
          <Stack direction="row" spacing={1} alignItems="center" sx={{ height: "100%" }}>
            <Avatar sx={{ width: 24, height: 24, fontSize: 12 }}>
              {String(params.value ?? "?").slice(0, 1)}
            </Avatar>
            <Typography variant="body2" noWrap>
              {params.value ? `#${params.value}` : "-"}
            </Typography>
          </Stack>
        ),
      },
      { field: "createdAt", headerName: "생성일시", type: "datetime", flex: 1, sortable: true, filter: false },
      {
        field: "updatedBy",
        headerName: "수정자",
        flex: 0.75,
        sortable: true,
        filter: false,
        cellRenderer: (params: ICellRendererParams<TemplateSummaryDto>) => (
          <Stack direction="row" spacing={1} alignItems="center" sx={{ height: "100%" }}>
            <Avatar sx={{ width: 24, height: 24, fontSize: 12 }}>
              {String(params.value ?? "?").slice(0, 1)}
            </Avatar>
            <Typography variant="body2" noWrap>
              {params.value ? `#${params.value}` : "-"}
            </Typography>
          </Stack>
        ),
      },
      { field: "updatedAt", headerName: "수정일시", type: "datetime", flex: 1, sortable: true, filter: false },
    ],
    [navigate]
  );

  const gridOptions = useMemo(
    () => ({
      rowSelection: { mode: "multiRow" as const, enableClickSelection: false, checkboxes: true, headerCheckbox: false },
      suppressRowClickSelection: true,
      selectionColumnDef: {
        width: 65,
        minWidth: 65,
        maxWidth: 65,
        pinned: "left" as const,
        sortable: false,
        filter: false,
        resizable: false,
      },
      rowMultiSelectWithClick: true,
    }),
    []
  );

  const gridEvents = useMemo(
    () => [
      {
        type: "selectionChanged",
        listener: (event: unknown) => {
          const rows = (event as SelectionChangedEvent<TemplateSummaryDto>).api.getSelectedRows();
          setSelectedIds(
            rows
              .map((row) => Number(row.templateId))
              .filter((id) => Number.isFinite(id) && id > 0)
          );
        },
      },
    ],
    []
  );

  function applyFilters() {
    dataSource.applyFilter({
      ...(keyword.trim() ? { q: keyword.trim(), fields: "name,subject" } : {}),
      ...(objectType.trim() ? { objectType: Number(objectType) } : {}),
      ...(objectId.trim() ? { objectId: Number(objectId) } : {}),
    });
    gridRef.current?.refresh();
  }

  async function handleDeleteSelected() {
    if (selectedIds.length === 0) return;
    const ok = await confirm({
      title: "삭제 확인",
      message: `선택한 ${selectedIds.length}개의 템플릿을 삭제하시겠습니까?`,
      okText: "삭제",
      cancelText: "취소",
    });
    if (!ok) return;

    try {
      await Promise.all(selectedIds.map((templateId) => reactTemplatesApi.delete(templateId)));
      toast.success("삭제 완료");
      gridRef.current?.deselectAll();
      setSelectedIds([]);
      gridRef.current?.refresh();
    } catch {
      toast.error("템플릿 삭제에 실패했습니다.");
    }
  }

  return (
    <Stack spacing={0.5}>
      <PageToolbar
        divider={false}
        breadcrumbs={["애플리케이션", "템플릿"]}
        label="템플릿을 조회하고 생성합니다."
        onRefresh={() => gridRef.current?.refresh()}
        searchPlaceholder="템플릿 검색"
        searchValue={keyword}
        onSearchValueChange={setKeyword}
        onSearch={applyFilters}
        actions={
          <>
            <Tooltip title="템플릿을 생성합니다.">
              <IconButton size="small" onClick={() => setCreateOpen(true)}>
                <AddOutlined fontSize="small" />
              </IconButton>
            </Tooltip>
            <Tooltip title={selectedCount > 0 ? "선택 삭제" : "삭제할 템플릿을 선택하세요"}>
              <span>
                <IconButton
                  size="small"
                  color="error"
                  disabled={selectedCount === 0}
                  onClick={() => void handleDeleteSelected()}
                >
                  <DeleteOutlineOutlined fontSize="small" />
                </IconButton>
              </span>
            </Tooltip>
          </>
        }
      />
      <Stack direction={{ xs: "column", md: "row" }} spacing={1} sx={{ py: 0.5 }}>
        <TextField
          label="객체 유형"
          type="number"
          value={objectType}
          onChange={(event) => setObjectType(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === "Enter") applyFilters();
          }}
          size="small"
        />
        <TextField
          label="객체 식별자"
          type="number"
          value={objectId}
          onChange={(event) => setObjectId(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === "Enter") applyFilters();
          }}
          size="small"
        />
      </Stack>
      <PageableGridContent<TemplateSummaryDto>
        ref={gridRef}
        datasource={dataSource}
        columns={columnDefs}
        options={gridOptions}
        events={gridEvents}
      />
      <CreateTemplateDialog
        open={createOpen}
        onClose={() => setCreateOpen(false)}
        onCreated={() => gridRef.current?.refresh()}
      />
    </Stack>
  );
}
