// src/views/studio/mgmt/application/files/FilesPage.vue
<template>
    <v-breadcrumbs class="pa-0" :items="['응용프로그램', '자원', '파일']" density="compact"></v-breadcrumbs>
    <PageToolbar title="파일" label="모듈별 첨부 파일을 관리합니다." @refresh="refresh" @delete="onDeleteSelected"
        :closeable="false" :divider="true" @upload="dialogs.upload.visible = true" :prepend-items="[
        ]" :items="[
            { icon: 'mdi-file-plus', tooltip: '새로운 파일 업로드', text: 'File Upload', variant: 'text', event: 'upload', color: 'blue', },
            { icon: 'mdi-delete', event: 'delete', color: 'error', tooltip: '선택 삭제', disabled:isDeleteDisabled },
            { icon: 'mdi-refresh', event: 'refresh', }]"></PageToolbar>
    <v-card density="compact" class="mt-1" variant="text">
        <v-alert closable rounded="0" icon="mdi-tooltip" class="mb-2 text-body-2"
            :text="`객체 유형은 모듈 식별 아이디 값입니다. 객체 식별자는 해당 모듈에 속하는 객체 아이디 값입니다. 예를 들어 객체 유셩이 문서(1) 이라면 각 문서들의 고유한 ID 값이 객체 식별자가 됩니다.`"
            type="info" max-height="100"></v-alert>
        <v-card-actions class="pa-0">
            <v-container fluid class="pa-0">
                <v-row>
                    <v-col cols="2">
                        <v-number-input v-model="objectType" :reverse="false" controlVariant="default" label="객체 유형" :hideInput="false"
                            hide-details variant="outlined" density="compact" :min="0" :inset="false"></v-number-input>
                    </v-col>
                    <v-col cols="2">
                        <v-number-input v-model="objectId" :reverse="false" controlVariant="default" label="객체 식별자" :hideInput="false"
                            hide-details variant="outlined" density="compact" :min="0" :inset="false"></v-number-input>
                    </v-col>
                    <v-col>
                        <v-text-field v-model="q" label="검색어" placeholder="파일 이름을 입력하세요." @keydown.enter="onSearchClick" hide-details variant="outlined"
                            density="compact">
                            <template v-slot:append>
                                <v-btn icon="mdi-text-search" variant="tonal"></v-btn>
                            </template>
                        </v-text-field>
                    </v-col>
                </v-row>
            </v-container>
        </v-card-actions>
    </v-card>
    <PageableGridContent ref="pageableGridContentRef" @filter-actived="onPageableGridFilterActived"
        :datasource="dataStore" :columns="columnDefs" :options="gridOptions" :events="gridEvents">
    </PageableGridContent>
    <FileUploadDialog v-model="dialogs.upload.visible" :attachmentId="0" @close="dialogs.upload.visible = false"
        @complete="refresh"></FileUploadDialog>
    <FileDialog v-model="dialogs.edit.visible" :attachmentId="dialogs.edit.attachmentId"
        @close="dialogs.edit.visible = false" @updated="refresh">
    </FileDialog>

</template>
<script setup lang="ts">
import PageToolbar from '@/components/bars/PageToolbar.vue';
import { usePageableFilesStore } from '@/stores/studio/mgmt/files.store';
import type { AttachmentDto } from '@/types/studio/files';
import { computed, onMounted, ref } from 'vue';
import type { ColDef, GridOptions, SelectionChangedEvent } from 'ag-grid-community';
import { formatDataSize } from '@/utils/helpers';
import PageableGridContent from '@/components/ag-grid/PageableGridContent.vue';
import { useConfirm } from '@/plugins/confirm';
import { useToast } from '@/plugins/toast';
import FileUploadDialog from './FileUploadDialog.vue';
import FileDialog from './FileDialog.vue';
import UserCellRenderer from '@/components/ag-grid/renderer/UserCellRenderer.vue';
import { useNavStore } from '@/stores/studio/mgmt/nav.store';
import { deleteFileById } from '@/data/studio/mgmt/files';
import { resolveAxiosError } from '@/utils/helpers';

const dataStore = usePageableFilesStore();
const confirm = useConfirm();
const toast = useToast();
const nav = useNavStore();

// grid 
// define grid columns
const columnDefs: ColDef[] = [
    { field: 'attachmentId', headerName: 'ID', filter: false, sortable: true, type: "number", maxWidth: 100},
    {
        field: 'name', headerName: '파일', filter: false, sortable: true, type: "hyperlinks", flex: 2, cellRendererParams: {
            mode: 'callback',
            labelClassName: "ag-link__label hover:underline",
            onClick: async (row: AttachmentDto) => {
                dialogs.value.edit.attachmentId = row.attachmentId;
                dialogs.value.edit.visible = true;
            },
        }
    }, 
    { field: 'size', headerName: '크기', filter: false, type: 'number', flex: 1, valueFormatter: formatDataSize },
    { field: 'contentType', headerName: '콘텐츠 종류', filter: false, type: 'text', flex: 1 },
    { field: 'createdBy', headerName: '생성자', filter: false, cellRenderer: UserCellRenderer, flex: 1 },
    { field: 'createdAt', headerName: '생성일시', filter: false, type: 'datetime', flex: 1 },
];
const gridOptions: GridOptions = {
    rowSelection: { mode: 'multiRow', enableClickSelection: true, checkboxes: true, headerCheckbox: false },
    selectionColumnDef: {
        width: 65,
        minWidth: 65,
        maxWidth: 65,
        pinned: 'left',
        sortable: false,
        filter: false,
        resizable: false,
    },
    rowMultiSelectWithClick: true,
};
const pageableGridContentRef = ref<InstanceType<typeof PageableGridContent> | null>(null);
const filtersActive = ref(false);
const selectedCount = ref(0);
const selectedIds = ref<number[]>([]);
const gridEvents = [
    {
        type: 'selectionChanged',
        listener: (event: SelectionChangedEvent) => {
            const rows = event.api.getSelectedRows() as Array<{ attachmentId?: number }>;
            selectedCount.value = rows.length;
            selectedIds.value = rows
                .map((row) => Number(row.attachmentId))
                .filter((id) => Number.isFinite(id) && id > 0);
        },
    },
];
const isDeleteDisabled = computed(() => selectedCount.value === 0);
function onPageableGridFilterActived(event: any) {
    filtersActive.value = event;
}
const refresh = () => {
    pageableGridContentRef.value?.refresh();
}

const dialogs = ref({
    upload: { visible: false },
    edit: { visible: false, attachmentId: 0 },
});

const onDeleteSelected = async () => {
    const ids = selectedIds.value;
    if (ids.length === 0) return;
    const ok = await confirm({
        title: '삭제 확인',
        message: `선택한 ${ids.length}개의 파일을 삭제하시겠습니까?`,
        okText: '삭제',
        cancelText: '취소',
        color: 'error',
    });
    if (!ok) return;
    try {
        await Promise.all(ids.map((id) => deleteFileById(id)));
        toast.success('삭제 완료');
        pageableGridContentRef.value?.deselectAll();
        refresh();
    } catch (e) {
        toast.error(resolveAxiosError(e));
    }
};

const q = ref<string | null>(null) 
const objectType = ref<number | null>(null)
const objectId = ref<number | null>(null) 
// 수동 조회 버튼
function onSearchClick() {
    const params: Record<string, any> = {}
    if (q.value) {
        params.keyword = q.value
    }
    if (objectType.value != null) {
        params.objectType = objectType.value
    }
    if (objectId.value != null) {
        params.objectId = objectId.value
    }
    dataStore.setFilter(params);
    refresh();
}

onMounted(() => {
    if( nav.previous?.name === 'FileDetails' && dataStore.page > 0){
        pageableGridContentRef.value?.goToPreviousPage();
    }
});

</script>

// src/react/pages/files/FilesPage.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { Alert, Avatar, Box, IconButton, Stack, TextField, Tooltip, Typography } from "@mui/material";
import DeleteOutlineIcon from "@mui/icons-material/DeleteOutline";
import UploadFileIcon from "@mui/icons-material/UploadFile";
import type { ColDef, ICellRendererParams } from "ag-grid-community";
import type { SelectionChangedEvent } from "ag-grid-community";
import { PageToolbar } from "@/react/components/page/PageToolbar";
import { PageableGridContent } from "@/react/components/ag-grid";
import type { PageableGridContentHandle } from "@/react/components/ag-grid/types";
import { ReactPageDataSource } from "@/react/pages/admin/datasource";
import { reactFilesApi } from "@/react/pages/files/api";
import { FileDetailDialog } from "@/react/pages/files/FileDetailDialog";
import { FileUploadDialog } from "@/react/pages/files/FileUploadDialog";
import { filesQueryKeys } from "@/react/pages/files/queryKeys";
import type { AttachmentDto } from "@/types/studio/files";
import { API_BASE_URL } from "@/config/backend";

function formatFileSize(size: number) {
  if (size < 1024) return `${size} B`;
  if (size < 1024 * 1024) return `${(size / 1024).toFixed(1)} KB`;
  return `${(size / (1024 * 1024)).toFixed(1)} MB`;
}

class FilesDataSource extends ReactPageDataSource<AttachmentDto> {
  constructor() {
    super("/api/mgmt/files");
  }
}

function SelectionCheckbox({
  checked,
  indeterminate = false,
  ariaLabel,
  onChange,
}: {
  checked: boolean;
  indeterminate?: boolean;
  ariaLabel: string;
  onChange: (checked: boolean) => void;
}) {
  const inputRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.indeterminate = indeterminate;
    }
  }, [indeterminate]);

  return (
    <input
      ref={inputRef}
      type="checkbox"
      aria-label={ariaLabel}
      checked={checked}
      onChange={(event) => onChange(event.target.checked)}
      onClick={(event) => event.stopPropagation()}
      style={{
        width: 16,
        height: 16,
        margin: 0,
        accentColor: "#1565c0",
        cursor: "pointer",
      }}
    />
  );
}

function getDisplayedSelectionState(api: {
  getLastDisplayedRowIndex: () => number;
  getDisplayedRowAtIndex: (index: number) => { isSelected: () => boolean; setSelected: (selected: boolean) => void } | undefined;
}) {
  const lastIndex = api.getLastDisplayedRowIndex();
  if (lastIndex < 0) {
    return { displayedCount: 0, selectedCount: 0 };
  }

  let displayedCount = 0;
  let selectedCount = 0;
  for (let index = 0; index <= lastIndex; index += 1) {
    const row = api.getDisplayedRowAtIndex(index);
    if (!row) continue;
    displayedCount += 1;
    if (row.isSelected()) {
      selectedCount += 1;
    }
  }

  return { displayedCount, selectedCount };
}

function toggleDisplayedRows(
  api: {
    getLastDisplayedRowIndex: () => number;
    getDisplayedRowAtIndex: (index: number) => { isSelected: () => boolean; setSelected: (selected: boolean) => void } | undefined;
  },
  selected: boolean
) {
  const lastIndex = api.getLastDisplayedRowIndex();
  for (let index = 0; index <= lastIndex; index += 1) {
    api.getDisplayedRowAtIndex(index)?.setSelected(selected);
  }
}

export function FilesPage() {
  const queryClient = useQueryClient();
  const gridRef = useRef<PageableGridContentHandle<AttachmentDto>>(null);
  const dataSource = useMemo(() => new FilesDataSource(), []);
  const [keyword, setKeyword] = useState("");
  const [objectType, setObjectType] = useState("");
  const [objectId, setObjectId] = useState("");
  const [dialogOpen, setDialogOpen] = useState(false);
  const [detailAttachmentId, setDetailAttachmentId] = useState<number | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);
  const [selectedIds, setSelectedIds] = useState<number[]>([]);
  const [displayedCount, setDisplayedCount] = useState(0);
  const selectedCount = selectedIds.length;

  function renderHeaderCheckbox(api?: {
    getLastDisplayedRowIndex: () => number;
    getDisplayedRowAtIndex: (index: number) => { isSelected: () => boolean; setSelected: (selected: boolean) => void } | undefined;
  }) {
    const currentState = api
      ? getDisplayedSelectionState(api)
      : { displayedCount, selectedCount };
    const allDisplayedSelected =
      currentState.displayedCount > 0 &&
      currentState.selectedCount === currentState.displayedCount;
    const partiallySelected =
      currentState.selectedCount > 0 &&
      currentState.selectedCount < currentState.displayedCount;

    return (
      <Box sx={{ width: "100%", display: "flex", justifyContent: "center" }}>
        <SelectionCheckbox
          ariaLabel="전체 선택"
          checked={allDisplayedSelected}
          indeterminate={partiallySelected}
          onChange={() => {
            if (api) {
              toggleDisplayedRows(api, !allDisplayedSelected);
            }
          }}
        />
      </Box>
    );
  }

  const columnDefs = useMemo<ColDef<AttachmentDto>[]>(
    () => [
      {
        colId: "rowSelect",
        headerName: "",
        width: 40,
        minWidth: 40,
        maxWidth: 40,
        pinned: "left",
        sortable: false,
        resizable: false,
        suppressMovable: true,
        lockPosition: true,
        cellClass: "selection-column-centered",
        headerClass: "selection-column-centered",
        headerComponent: (props: {
          api: {
            getLastDisplayedRowIndex: () => number;
            getDisplayedRowAtIndex: (index: number) => { isSelected: () => boolean; setSelected: (selected: boolean) => void } | undefined;
          };
        }) => renderHeaderCheckbox(props.api),
        cellRenderer: (params: ICellRendererParams<AttachmentDto>) => {
          const checked = params.node.isSelected();

          return (
            <Box sx={{ width: "100%", display: "flex", justifyContent: "center" }}>
              <SelectionCheckbox
                ariaLabel="행 선택"
                checked={checked}
                onChange={(nextChecked) => params.node.setSelected(nextChecked)}
              />
            </Box>
          );
        },
      },
      {
        field: "attachmentId",
        headerName: "ID",
        width: 64,
        minWidth: 64,
        maxWidth: 64,
        sortable: true,
        type: "number",
        filter: false,
        cellStyle: { textAlign: "center" },
        headerClass: "id-column-centered",
        cellClass: "id-column-centered",
      },
      {
        field: "name",
        headerName: "파일",
        flex: 1.6,
        sortable: true,
        filter: false,
        cellRenderer: (params: ICellRendererParams<AttachmentDto>) => (
          <Box
            component="button"
            type="button"
            onClick={(event) => {
              event.stopPropagation();
              setDetailAttachmentId(params.data?.attachmentId ?? null);
            }}
            sx={{
              border: 0,
              p: 0,
              bgcolor: "transparent",
              color: "primary.main",
              cursor: "pointer",
              font: "inherit",
              textAlign: "left",
              "&:hover": { textDecoration: "underline" },
            }}
          >
            {params.value}
          </Box>
        ),
      },
      {
        field: "size",
        headerName: "크기",
        flex: 0.45,
        sortable: true,
        type: "number",
        filter: false,
        valueFormatter: (params) => formatFileSize(Number(params.value ?? 0)),
      },
      { field: "contentType", headerName: "콘텐츠 타입", flex: 0.8, sortable: true, filter: false },
      {
        field: "createdBy",
        headerName: "생성자",
        flex: 0.8,
        filter: false,
        cellRenderer: (params: ICellRendererParams<AttachmentDto>) => (
          <Box sx={{ display: "flex", gap: 1, alignItems: "center", minWidth: 0, height: "100%" }}>
            <Avatar
              src={
                params.value?.username
                  ? `${API_BASE_URL}/api/profile/${encodeURIComponent(params.value.username)}/avatar`
                  : undefined
              }
              sx={{ width: 24, height: 24, fontSize: 12 }}
            >
              {params.value?.username?.slice(0, 1).toUpperCase() ?? "?"}
            </Avatar>
            <Typography variant="body2" noWrap>
              {params.value?.username ?? "-"}
            </Typography>
          </Box>
        ),
      },
      { field: "createdAt", headerName: "생성일시", flex: 0.75, sortable: true, type: "datetime", filter: false },
    ],
    [displayedCount, selectedCount]
  );

  const gridOptions = useMemo(
    () => ({
      rowSelection: {
        mode: "multiRow" as const,
        enableClickSelection: false,
        checkboxes: false,
        headerCheckbox: false,
      },
      suppressRowClickSelection: true,
      rowMultiSelectWithClick: true,
    }),
    []
  );

  const gridEvents = useMemo(
    () => [
      {
        type: "selectionChanged",
        listener: (event: unknown) => {
          const rows = (event as SelectionChangedEvent<AttachmentDto>).api.getSelectedRows();
          setSelectedIds(
            rows
              .map((row) => Number(row.attachmentId))
              .filter((id) => Number.isFinite(id) && id > 0)
          );
          setDisplayedCount((event as SelectionChangedEvent<AttachmentDto>).api.getDisplayedRowCount());
        },
      },
      {
        type: "modelUpdated",
        listener: (event: { api: { getDisplayedRowCount: () => number; refreshHeader?: () => void } }) => {
          setDisplayedCount(event.api.getDisplayedRowCount());
          event.api.refreshHeader?.();
        },
      },
    ],
    []
  );

  function applyFilters() {
    dataSource.applyFilter({
      ...(keyword.trim() ? { keyword: keyword.trim() } : {}),
      ...(objectType.trim() ? { objectType: Number(objectType) } : {}),
      ...(objectId.trim() ? { objectId: Number(objectId) } : {}),
    });
    gridRef.current?.refresh();
  }

  const handleDeleteSelected = async () => {
    if (selectedIds.length === 0) return;
    const confirmed = window.confirm(`선택한 ${selectedIds.length}개의 파일을 삭제하시겠습니까?`);
    if (!confirmed) {
      return;
    }

    setActionError(null);
    try {
      await Promise.all(selectedIds.map((attachmentId) => reactFilesApi.deleteById(attachmentId)));
      await queryClient.invalidateQueries({ queryKey: filesQueryKeys.all });
      gridRef.current?.deselectAll();
      setSelectedIds([]);
      gridRef.current?.refresh();
    } catch (error) {
      setActionError(error instanceof Error ? error.message : "파일 삭제에 실패했습니다.");
    }
  };

  return (
    <>
      <Stack spacing={0.5}>
        <PageToolbar
          divider={false}
          breadcrumbs={["애플리케이션", "파일"]}
          label="파일을 검색하고 업로드 경로를 관리합니다."
          onRefresh={() => gridRef.current?.refresh()}
          searchPlaceholder="파일 검색"
          searchValue={keyword}
          onSearchValueChange={setKeyword}
          onSearch={applyFilters}
          actions={
            <>
              <Tooltip title="새로운 파일 업로드">
                <IconButton size="small" onClick={() => setDialogOpen(true)}>
                  <UploadFileIcon fontSize="small" />
                </IconButton>
              </Tooltip>
              <Tooltip title={selectedCount > 0 ? "선택 삭제" : "삭제할 파일을 선택하세요"}>
                <span>
                  <IconButton
                    size="small"
                    color="error"
                    disabled={selectedCount === 0}
                    onClick={() => void handleDeleteSelected()}
                  >
                    <DeleteOutlineIcon fontSize="small" />
                  </IconButton>
                </span>
              </Tooltip>
            </>
          }
        />

        <Alert severity="info">
          객체 유형은 모듈 식별 아이디 값입니다. 객체 식별자는 해당 모듈에 속하는 객체 아이디
          값입니다. 예를 들어 객체 유형이 문서(1)라면 각 문서의 고유한 ID 값이 객체 식별자가
          됩니다.
        </Alert>

        <Stack direction={{ xs: "column", md: "row" }} spacing={1} sx={{ py: 0.5 }}>
          <TextField
            label="객체 유형"
            type="number"
            value={objectType}
            onChange={(event) => setObjectType(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter") applyFilters();
            }}
            size="small"
          />
          <TextField
            label="객체 식별자"
            type="number"
            value={objectId}
            onChange={(event) => setObjectId(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter") applyFilters();
            }}
            size="small"
          />
        </Stack>

        {actionError ? <Alert severity="error">{actionError}</Alert> : null}

        <PageableGridContent<AttachmentDto>
          ref={gridRef}
          datasource={dataSource}
          columns={columnDefs}
          options={gridOptions}
          events={gridEvents}
        />
      </Stack>

      <FileUploadDialog
        open={dialogOpen}
        initialObjectId={objectId.trim() === "" ? null : Number(objectId)}
        initialObjectType={objectType.trim() === "" ? null : Number(objectType)}
        onClose={() => setDialogOpen(false)}
        onUploaded={async () => {
          await queryClient.invalidateQueries({ queryKey: filesQueryKeys.all });
          gridRef.current?.refresh();
        }}
      />
      {detailAttachmentId ? (
        <FileDetailDialog
          open={detailAttachmentId !== null}
          onClose={() => setDetailAttachmentId(null)}
          attachmentId={detailAttachmentId}
        />
      ) : null}
    </>
  );
}
