// src/components/ag-grid/GridContent.vue
<template>
  <div ref="gridContainer" class="ag-theme-adapted" :style="{ width: '100%', height: gridHeight + 'px' }">
    <AgGridVue class="ag-theme-adapted" style="width: 100%; height: 100%" :gridOptions="gridOptionsDefs"
      :rowSelection="rowSelectionDefs" :columnDefs="columnDefs" :rowData="rowData" @row-selected="onRowSelected"
      @row-data-updated="onRowDataUpdated" @selectionChanged="onSelectionChanged" @grid-ready="onGridReady" :defaultColDef="{ resizable: true }"></AgGridVue>
  </div>
</template>
<script setup lang="ts">
import type {
  ColDef,
  GridOptions,
  GridApi,
  SelectionChangedEvent,
  RowSelectionOptions,
} from 'ag-grid-community';
import { AgGridVue } from 'ag-grid-vue3'; // Vue Data Grid Component
import { ref, onMounted, computed, watch, nextTick } from 'vue';
import gridOptions from '@/components/ag-grid/ag-grid-options';

interface Listener {
  type: string;
  listener: (event: any) => void;
}
const props = defineProps<{
  columns?: ColDef[];
  options?: GridOptions;
  events?: Listener[];
  rowSelection?: RowSelectionOptions | "single" | "multiple";
  rowData: any[];
  autoResize?: boolean;
  height?: number | undefined;
}>();

// Grid options 설정
const gridOptionsDefs = computed<GridOptions>(() => props.options || gridOptions);
const rowSelectionDefs = computed<RowSelectionOptions | "single" | "multiple">(
  () => props.rowSelection || 'single'
);

// Grid columns 설정
const columnDefs = computed<ColDef[]>(() => props.columns || []);

// 그리드 동적 크기 조정
const gridContainer = ref<HTMLElement | null>(null);
const gridHeight = ref(props.height ?? 400); // initial height 
const resizeGrid = () => {
  if (gridContainer.value) {
    gridHeight.value = window.innerHeight - gridContainer.value.getBoundingClientRect().top - 25; // Adjust as needed
    gridApi.value?.sizeColumnsToFit();
  }
};

//  Grid API 설정
const gridApi = ref<GridApi | null>();
const onGridReady = (params: any) => {
  gridApi.value = params.api;
  props.events?.forEach((item: Listener) =>
    params.api.addEventListener(item.type, item.listener)
  );
  if (props.autoResize || props.height == null) resizeGrid();
};

// 필터 관리
const emit = defineEmits(['filterActived', 'rowSelected']);
const filtersActive = ref(false);

const onRowSelected = (event: any) => {
  emit('rowSelected', event);
};

// filtersActive 값이 변경되면 filtersActive 이벤트 발생
watch(filtersActive, (val) => {
  emit('filterActived', val);
});

// 데이터 새로고침
function refresh() {
  gridApi.value?.refreshInfiniteCache();
}

//필터 초기화
const clearFilters = () => {
  gridApi.value?.setFilterModel({});
  gridApi.value?.onFilterChanged();
};

// 선택된 행 관리
const selectedItems = ref<any[]>([]);
const onSelectionChanged = (params: SelectionChangedEvent) => {
  selectedItems.value = params.api.getSelectedRows() as [];
};
const selectedRows = () => {
  return selectedItems.value;
};
const displayedRowCount = () => {
  return gridApi.value?.getDisplayedRowCount() ?? 0;
};

const reservedScrollIndex = ref<number>(0);
const reserveScrollTo = (last: number = 0) => {
  if (last > 0)
    reservedScrollIndex.value = last;
};

async function onRowDataUpdated() {
  if (reservedScrollIndex.value > 0) {
    await nextTick()
    gridApi.value?.ensureIndexVisible(reservedScrollIndex.value, 'middle');
    reservedScrollIndex.value = -1;
  }
}

const loading = (loading: boolean = false) => {
  gridApi.value?.setGridOption('loading', loading);
}

onMounted(async () => {
  // Initial resize 
  if (props.autoResize || props.height == null) resizeGrid();
});

defineExpose({
  refresh,
  filtersActive,
  clearFilters,
  selectedRows,
  displayedRowCount,
  reserveScrollTo,
  loading,
});

</script>

// src/react-components/ag-grid/GridContent.tsx
// src/react-components/ag-grid/GridContent.tsx
import React, { useRef, useState, useEffect, useCallback, useMemo, useImperativeHandle, forwardRef } from 'react';
import { AgGridReact } from 'ag-grid-react';
import { ColDef, GridOptions, GridApi, SelectionChangedEvent, RowSelectionOptions, IRowNode } from 'ag-grid-community';

import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css'; // This can be replaced with a custom theme if needed

interface Listener {
  type: string;
  listener: (event: any) => void;
}

interface GridContentProps {
  columns?: ColDef[];
  options?: GridOptions;
  events?: Listener[];
  rowSelection?: RowSelectionOptions | "single" | "multiple";
  rowData: any[];
  autoResize?: boolean;
  height?: number;
  onRowSelected?: (event: { data: any; node: IRowNode; }) => void;
  onFilterActived?: (isActive: boolean) => void;
}

export interface GridContentRef {
  refresh: () => void;
  clearFilters: () => void;
  selectedRows: () => any[];
  displayedRowCount: () => number;
  reserveScrollTo: (last: number) => void;
  loading: (isLoading: boolean) => void;
}

const defaultGridOptions: GridOptions = {
  // Default options, can be overridden by props.options
  // Vue version used '@/components/ag-grid/ag-grid-options' for defaults
  // For now, using a minimal default, specific overrides should come from props.options
};

const GridContent = forwardRef<GridContentRef, GridContentProps>(({
  columns,
  options,
  events,
  rowSelection = 'single',
  rowData,
  autoResize = false,
  height,
  onRowSelected,
  onFilterActived,
}, ref) => {
  const gridRef = useRef<AgGridReact>(null);
  const gridApi = useRef<GridApi | null>(null);
  const [gridHeight, setGridHeight] = useState(height ?? 400); // initial height
  const [filtersActive, setFiltersActive] = useState(false);
  const [selectedItems, setSelectedItems] = useState<any[]>([]);
  const reservedScrollIndex = useRef<number>(0);

  const columnDefs = useMemo<ColDef[]>(() => columns || [], [columns]);
  const gridOptionsDefs = useMemo<GridOptions>(() => ({ ...defaultGridOptions, ...options }), [options]);

  const resizeGrid = useCallback(() => {
    if (gridRef.current && gridRef.current.api && gridRef.current.eGridDiv) {
      // Mimic Vue's dynamic height adjustment
      const containerTop = gridRef.current.eGridDiv.getBoundingClientRect().top;
      setGridHeight(window.innerHeight - containerTop - 25); // Adjust as needed
      gridRef.current.api.sizeColumnsToFit();
    }
  }, []);

  const onGridReady = useCallback((params: { api: GridApi; }) => {
    gridApi.current = params.api;
    events?.forEach((item: Listener) =>
      params.api.addEventListener(item.type, item.listener)
    );
    if (autoResize || height == null) {
      resizeGrid();
    }
  }, [events, autoResize, height, resizeGrid]);

  const handleSelectionChanged = useCallback((event: SelectionChangedEvent) => {
    const newSelectedRows = event.api.getSelectedRows();
    setSelectedItems(newSelectedRows);
  }, []);

  const handleRowSelected = useCallback((event: any) => {
    // Vue version emitted specific event, mimick that for parent
    if (onRowSelected) {
      onRowSelected(event);
    }
  }, [onRowSelected]);

  const onRowDataUpdated = useCallback(() => {
    if (reservedScrollIndex.current > 0 && gridApi.current) {
      gridApi.current.ensureIndexVisible(reservedScrollIndex.current, 'middle');
      reservedScrollIndex.current = -1; // Reset after use
    }
  }, []);

  // Expose methods to parent component using ref
  useImperativeHandle(ref, () => ({
    refresh: () => {
      gridApi.current?.refreshInfiniteCache();
    },
    clearFilters: () => {
      gridApi.current?.setFilterModel(null); // setFilterModel({}) clears, null for all filters
      gridApi.current?.onFilterChanged();
    },
    selectedRows: () => {
      return selectedItems;
    },
    displayedRowCount: () => {
      return gridApi.current?.getDisplayedRowCount() ?? 0;
    },
    reserveScrollTo: (last: number = 0) => {
      if (last > 0) {
        reservedScrollIndex.current = last;
      }
    },
    loading: (isLoading: boolean = false) => {
      // AG Grid React has its own loading overlay mechanisms,
      // this might need adaptation based on how the Vue version used it.
      // For now, a placeholder, as setGridOption('loading') is not standard.
      // A common way is to use custom loading overlay components or context.
      console.warn('AG Grid React `loading` method needs specific implementation based on actual loading strategy.');
    },
  }));

  // Watch for changes in window size for autoResize
  useEffect(() => {
    if (autoResize || height == null) {
      window.addEventListener('resize', resizeGrid);
      return () => window.removeEventListener('resize', resizeGrid);
    }
  }, [autoResize, height, resizeGrid]);

  // Propagate filter status
  useEffect(() => {
    if (onFilterActived) {
      // AG Grid v30+ has filterChanged event, can check if filters are active
      const currentFiltersActive = gridApi.current?.isAnyFilterPresent() || false;
      if (currentFiltersActive !== filtersActive) {
        setFiltersActive(currentFiltersActive);
        onFilterActived(currentFiltersActive);
      }
    }
  }, [filtersActive, onFilterActived]); // This effect might need to be triggered by a grid event

  return (
    <div style={{ width: '100%', height: gridHeight + 'px' }} className="ag-theme-alpine">
      <AgGridReact
        ref={gridRef}
        rowData={rowData}
        columnDefs={columnDefs}
        gridOptions={gridOptionsDefs}
        rowSelection={rowSelection as any} // Cast as any because type definition might be slightly off for string literals
        onGridReady={onGridReady}
        onSelectionChanged={handleSelectionChanged}
        onRowClicked={handleRowSelected} // Assuming row-selected means rowClicked for simple selection
        onRowDataUpdated={onRowDataUpdated}
        defaultColDef={{ resizable: true }}
        // onFilterChanged={() => { /* logic to update filtersActive state */ }} // Need to hook this up
      />
    </div>
  );
});

export default GridContent;
