// src/components/ag-grid/GridContent.vue
<template>
  <div ref="gridContainer" class="ag-theme-adapted" :style="{ width: '100%', height: gridHeight + 'px' }">
    <AgGridVue class="ag-theme-adapted" style="width: 100%; height: 100%" :gridOptions="gridOptionsDefs"
      :rowSelection="rowSelectionDefs" :columnDefs="columnDefs" :rowData="rowData" @row-selected="onRowSelected"
      @row-data-updated="onRowDataUpdated" @selectionChanged="onSelectionChanged" @grid-ready="onGridReady" :defaultColDef="{ resizable: true }"></AgGridVue>
  </div>
</template>
<script setup lang="ts">
import type {
  ColDef,
  GridOptions,
  GridApi,
  SelectionChangedEvent,
  RowSelectionOptions,
} from 'ag-grid-community';
import { AgGridVue } from 'ag-grid-vue3'; // Vue Data Grid Component
import { ref, onMounted, computed, watch, nextTick } from 'vue';
import gridOptions from '@/components/ag-grid/ag-grid-options';

interface Listener {
  type: string;
  listener: (event: any) => void;
}
const props = defineProps<{
  columns?: ColDef[];
  options?: GridOptions;
  events?: Listener[];
  rowSelection?: RowSelectionOptions | "single" | "multiple";
  rowData: any[];
  autoResize?: boolean;
  height?: number | undefined;
}>();

// Grid options 설정
const gridOptionsDefs = computed<GridOptions>(() => props.options || gridOptions);
const rowSelectionDefs = computed<RowSelectionOptions | "single" | "multiple">(
  () => props.rowSelection || 'single'
);

// Grid columns 설정
const columnDefs = computed<ColDef[]>(() => props.columns || []);

// 그리드 동적 크기 조정
const gridContainer = ref<HTMLElement | null>(null);
const gridHeight = ref(props.height ?? 400); // initial height 
const resizeGrid = () => {
  if (gridContainer.value) {
    gridHeight.value = window.innerHeight - gridContainer.value.getBoundingClientRect().top - 25; // Adjust as needed
    gridApi.value?.sizeColumnsToFit();
  }
};

//  Grid API 설정
const gridApi = ref<GridApi | null>();
const onGridReady = (params: any) => {
  gridApi.value = params.api;
  props.events?.forEach((item: Listener) =>
    params.api.addEventListener(item.type, item.listener)
  );
  if (props.autoResize || props.height == null) resizeGrid();
};

// 필터 관리
const emit = defineEmits(['filterActived', 'rowSelected']);
const filtersActive = ref(false);

const onRowSelected = (event: any) => {
  emit('rowSelected', event);
};

// filtersActive 값이 변경되면 filtersActive 이벤트 발생
watch(filtersActive, (val) => {
  emit('filterActived', val);
});

// 데이터 새로고침
function refresh() {
  gridApi.value?.refreshInfiniteCache();
}

//필터 초기화
const clearFilters = () => {
  gridApi.value?.setFilterModel({});
  gridApi.value?.onFilterChanged();
};

// 선택된 행 관리
const selectedItems = ref<any[]>([]);
const onSelectionChanged = (params: SelectionChangedEvent) => {
  selectedItems.value = params.api.getSelectedRows() as [];
};
const selectedRows = () => {
  return selectedItems.value;
};
const displayedRowCount = () => {
  return gridApi.value?.getDisplayedRowCount() ?? 0;
};

const reservedScrollIndex = ref<number>(0);
const reserveScrollTo = (last: number = 0) => {
  if (last > 0)
    reservedScrollIndex.value = last;
};

async function onRowDataUpdated() {
  if (reservedScrollIndex.value > 0) {
    await nextTick()
    gridApi.value?.ensureIndexVisible(reservedScrollIndex.value, 'middle');
    reservedScrollIndex.value = -1;
  }
}

const loading = (loading: boolean = false) => {
  gridApi.value?.setGridOption('loading', loading);
}

onMounted(async () => {
  // Initial resize 
  if (props.autoResize || props.height == null) resizeGrid();
});

defineExpose({
  refresh,
  filtersActive,
  clearFilters,
  selectedRows,
  displayedRowCount,
  reserveScrollTo,
  loading,
});

</script>

// src/react/components/ag-grid/GridContent.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from "react";
import type {
  ColDef,
  GridApi,
  GridOptions,
  GridReadyEvent,
  SelectionChangedEvent,
} from "ag-grid-community";
import { AgGridReact } from "ag-grid-react";
import { defaultGridOptions } from "@/react/components/ag-grid/gridOptions";
import type {
  GridContentHandle,
  GridContentProps,
} from "@/react/components/ag-grid/types";
import {
  getAutoGridHeight,
  normalizeRowSelection,
} from "@/react/components/ag-grid/utils";
import "@/react/components/ag-grid/styles.css";

function GridContentInner<TData = unknown>(
  {
    columns,
    options,
    events,
    rowSelection,
    rowData,
    autoResize,
    height,
    onFilterActived,
    onRowSelected,
  }: GridContentProps<TData>,
  ref: React.ForwardedRef<GridContentHandle<TData>>
) {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const gridApiRef = useRef<GridApi<TData> | null>(null);
  const reservedScrollIndexRef = useRef(0);
  const [gridHeight, setGridHeight] = useState(height ?? 400);
  const [selectedItems, setSelectedItems] = useState<TData[]>([]);

  const shouldAutoResize = autoResize || height == null;
  const gridOptions = useMemo<GridOptions<TData>>(
    () => ({ ...defaultGridOptions, ...options }),
    [options]
  );
  const columnDefs = useMemo<ColDef<TData>[]>(() => columns ?? [], [columns]);
  const normalizedRowSelection = useMemo(
    () => normalizeRowSelection(rowSelection),
    [rowSelection]
  );

  const resizeGrid = useCallback(() => {
    if (!containerRef.current) {
      return;
    }

    setGridHeight(getAutoGridHeight(containerRef.current));
    gridApiRef.current?.sizeColumnsToFit();
  }, []);

  const handleGridReady = useCallback(
    (event: GridReadyEvent<TData>) => {
      gridApiRef.current = event.api;
      events?.forEach((listener) =>
        event.api.addEventListener(
          listener.type as Parameters<typeof event.api.addEventListener>[0],
          listener.listener as Parameters<typeof event.api.addEventListener>[1]
        )
      );

      if (shouldAutoResize) {
        resizeGrid();
      }
    },
    [events, resizeGrid, shouldAutoResize]
  );

  const handleSelectionChanged = useCallback(
    (event: SelectionChangedEvent<TData>) => {
      setSelectedItems(event.api.getSelectedRows());
    },
    []
  );

  useEffect(() => {
    if (reservedScrollIndexRef.current <= 0) {
      return;
    }

    gridApiRef.current?.ensureIndexVisible(reservedScrollIndexRef.current, "middle");
    reservedScrollIndexRef.current = -1;
  }, [rowData]);

  useEffect(() => {
    onFilterActived?.(false);
  }, [onFilterActived]);

  useEffect(() => {
    if (!shouldAutoResize) {
      return;
    }

    resizeGrid();
    window.addEventListener("resize", resizeGrid);

    return () => {
      window.removeEventListener("resize", resizeGrid);
    };
  }, [resizeGrid, shouldAutoResize]);

  useImperativeHandle(
    ref,
    () => ({
      refresh: () => {
        gridApiRef.current?.refreshCells({ force: true });
      },
      clearFilters: () => {
        gridApiRef.current?.setFilterModel(null);
        gridApiRef.current?.onFilterChanged();
      },
      selectedRows: () => selectedItems,
      displayedRowCount: () => gridApiRef.current?.getDisplayedRowCount() ?? 0,
      reserveScrollTo: (last = 0) => {
        if (last > 0) {
          reservedScrollIndexRef.current = last;
        }
      },
      loading: (loading = false) => {
        gridApiRef.current?.setGridOption("loading", loading);
      },
    }),
    [selectedItems]
  );

  return (
    <div
      ref={containerRef}
      className="ag-theme-material react-grid-host"
      style={{ width: "100%", height: gridHeight }}
    >
      <AgGridReact<TData>
        gridOptions={gridOptions}
        rowSelection={normalizedRowSelection}
        columnDefs={columnDefs}
        rowData={rowData}
        defaultColDef={{ resizable: true }}
        onRowSelected={onRowSelected}
        onSelectionChanged={handleSelectionChanged}
        onGridReady={handleGridReady}
      />
    </div>
  );
}

export const GridContent = forwardRef(GridContentInner) as <TData = unknown>(
  props: GridContentProps<TData> & {
    ref?: React.ForwardedRef<GridContentHandle<TData>>;
  }
) => React.ReactElement;
