// src/views/studio/mgmt/audit/LoginFailureLogPage.vue
<template>
    <v-breadcrumbs class="pa-0" :items="['시스템관리', '감사', '로그인 실패']" density="compact"></v-breadcrumbs>
    <PageToolbar title="" label="로그인 실패 이력" @refresh="refresh" :closeable="false" :divider="true" :prepend-items="[
    ]" :items="[
        { icon: 'mdi-refresh', event: 'refresh', }]"></PageToolbar>
    <v-card density="compact" variant="text" class="mt-1">
        <v-card-text class="pa-0">
            <v-row no-gutters class="pb-0 px-0 mb-0 pt-3">
                <v-col>
                    <v-menu v-model="dateMenuStart" :close-on-content-click="false" transition="scale-transition"
                        offset-y>
                        <template #activator="{ props }">
                            <v-text-field v-bind="props" label="시작일(포함)" prepend-inner-icon="mdi-calendar"
                                variant="outlined" density="compact" readonly class="mr-2"
                                :model-value="dateStartDisplay" placeholder="예: 2025년 10월 29일 (수)"
                                :error="!validRange" />
                        </template>
                        <v-date-picker v-model="dateStart" @update:modelValue="dateMenuStart = false"
                            show-adjacent-months :first-day-of-week="0" />
                    </v-menu>
                </v-col>
                <v-col>
                    <v-menu v-model="dateMenuEnd" :close-on-content-click="false" transition="scale-transition"
                        offset-y>
                        <template #activator="{ props }">
                            <v-text-field v-bind="props" label="종료일(포함)" prepend-inner-icon="mdi-calendar"
                                variant="outlined" density="compact" readonly class="mr-2" :model-value="dateEndDisplay"
                                placeholder="예: 2025년 10월 29일 (수)" :error="!validRange"
                                :messages="!validRange ? ['시작일이 종료일보다 늦을 수 없습니다.'] : []" />
                        </template>
                        <v-date-picker v-model="dateEnd" @update:modelValue="dateMenuEnd = false" show-adjacent-months
                            :first-day-of-week="0" />
                    </v-menu>
                </v-col>
                <v-col>
                    <v-text-field clearable variant="outlined" label="아이디" density="compact"
                        v-model="usernameLike" @keydown.enter="onSearchClick"></v-text-field>
                </v-col>
            </v-row> 
        </v-card-text>
        <v-card-actions class="pa-0 mt-0">
            <v-btn-toggle color="deep-purple-accent-3" rounded="5" group density="compact">
                <v-btn @click="setToday"><span class="hidden-sm-and-down">오늘</span></v-btn>
                <v-btn @click="set7days">7일</v-btn>
                <v-btn @click="set30days">30일</v-btn>
                <v-btn @click="set6Months">6개월</v-btn>
                <v-btn @click="setThisMonth">이번달</v-btn></v-btn-toggle>
            <v-spacer></v-spacer>
            <!-- <v-btn class="pr-5" width="100" variant="outlined" rounded="xl" prepend-icon="mdi-magnify" text="조회"
                :disabled="!validRange" @click="onSearchClick">
            </v-btn> -->
            <v-btn icon="mdi-text-search" variant="tonal" :disabled="!validRange" @click="onSearchClick"></v-btn>
        </v-card-actions>
    </v-card>
    <v-row>
        <v-col cols="12" md="12">
            <PageableGridContent @filter-actived="onPageableGridFilterActived" ref="pageableGridContentRef"
                :datasource="dataStore" :columns="columnDefs">
            </PageableGridContent>
        </v-col>
    </v-row>
</template>
<script setup lang="ts">
import PageableGridContent from '@/components/ag-grid/PageableGridContent.vue';
import PageToolbar from '@/components/bars/PageToolbar.vue';
import { usePageableLoginFailureLogStore } from '@/stores/studio/mgmt/audit.login-failure-log.store';
import type { ColDef } from 'ag-grid-community';
import { computed, onMounted, ref } from 'vue';

// grid 
const dataStore = usePageableLoginFailureLogStore();

// define grid columns
const columnDefs: ColDef[] = [
    { field: 'id', headerName: 'ID', filter: false, sortable: true, type: "number", flex: .25 },
    { field: 'occurredAt', headerName: '일시', filter: false, sortable: true, type: 'datetime', flex: .6 },
    { field: 'username', headerName: '아이디', filter: false, sortable: true, type: 'string', flex: .25 },
    { field: 'remoteIp', headerName: 'IP', filter: false, sortable: true, type: 'string', flex: .5 },
    { field: 'message', headerName: '메시지', filter: false, sortable: false, type: 'string', flex: 1 },
    { field: 'userAgent', headerName: 'UserAgent', filter: false, sortable: false, type: 'string', },
];

const pageableGridContentRef = ref<InstanceType<typeof PageableGridContent> | null>(null);
const filtersActive = ref(false);

function onPageableGridFilterActived(event: any) {
    filtersActive.value = event;
}
const refresh = () => {
    pageableGridContentRef.value?.refresh();
}
const fmtKo = new Intl.DateTimeFormat('ko-KR', {
    year: 'numeric', month: 'long', day: 'numeric',
    weekday: 'short', timeZone: 'Asia/Seoul',
});
const dateStartDisplay = computed(() => dateStart.value ? fmtKo.format(new Date(dateStart.value)) : '');
const dateEndDisplay = computed(() => dateEnd.value ? fmtKo.format(new Date(dateEnd.value)) : '');

const dateStart = ref<string | null>(null) // 'YYYY-MM-DD'
const dateEnd = ref<string | null>(null) // 'YYYY-MM-DD'
const dateMenuStart = ref(false)
const dateMenuEnd = ref(false)

// ====== 유틸: 로컬 날짜를 ISO(UTC)로 변환 ======
/**
 * YYYY-MM-DD -> 로컬타임 기준 00:00의 ISO UTC
 */
function startOfDayLocalToIso(dateStr: string): string {
    const [y = 0, m = 1, d = 1] = dateStr.split('-').map(Number)
    const dt = new Date(y, m - 1, d, 0, 0, 0, 0) // local
    return dt.toISOString()
}
/**
 * YYYY-MM-DD -> 로컬타임 기준 다음날 00:00의 ISO UTC (end-exclusive)
 */
function endOfDayExclusiveLocalToIso(dateStr: string): string {
    const [y = 0, m = 1, d = 1] = dateStr.split('-').map(Number)
    const dt = new Date(y, m - 1, d + 1, 0, 0, 0, 0) // 다음날 00:00
    return dt.toISOString()
}

const validRange = computed(() => {
    if (!dateStart.value || !dateEnd.value) return true
    return dateStart.value <= dateEnd.value
})

const queryFrom = computed(() => {
    if (!dateStart.value) return null
    return startOfDayLocalToIso(dateStart.value)
})
const queryTo = computed(() => {
    if (!dateEnd.value) return null
    return endOfDayExclusiveLocalToIso(dateEnd.value)
})


// 초기: 최근 7일
function setPreset(days: number) {
    const now = new Date()
    const end = new Date(now.getFullYear(), now.getMonth(), now.getDate()) // today
    const start = new Date(end)
    start.setDate(start.getDate() - (days - 1))
    dateStart.value = start.toISOString().slice(0, 10)
    dateEnd.value = end.toISOString().slice(0, 10)
}

// ====== 빠른 범위 ======
function setToday() { setPreset(1) }
function set7days() { setPreset(7) }
function set30days() { setPreset(30) }
function setThisMonth() {
    const now = new Date();
    const start = new Date(now.getFullYear(), now.getMonth(), 1)
    const end = new Date(now.getFullYear(), now.getMonth() + 1, 0)
    dateStart.value = start.toISOString().slice(0, 10)
    dateEnd.value = end.toISOString().slice(0, 10)
}

function set6Months() {
    const now = new Date()
    const start = new Date(now.getFullYear(), now.getMonth() - 6, now.getDate())
    const end = new Date(now.getFullYear(), now.getMonth(), now.getDate())
    dateStart.value = start.toISOString().slice(0, 10)
    dateEnd.value = end.toISOString().slice(0, 10)
}


const usernameLike = ref<string>();
// 수동 조회 버튼
function onSearchClick() {
    if (!validRange.value) return
    fetchPage();
}

async function fetchPage() {
    const params: Record<string, any> = {}
    if (queryFrom.value) params.from = queryFrom.value
    if (queryTo.value) params.to = queryTo.value
    if (usernameLike.value) params.usernameLike = usernameLike.value
    dataStore.setFilter(params);
    refresh();
}

onMounted(() => {
    setPreset(7)
});

</script>

// src/react/pages/audit/LoginFailureLogPage.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import {
  Box,
  Breadcrumbs,
  Button,
  ButtonGroup,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import {
  RefreshOutlined,
} from "@mui/icons-material";
import type { ColDef } from "ag-grid-community";
import { PageableGridContent } from "@/react/components/ag-grid";
import type { PageableGridContentHandle } from "@/react/components/ag-grid/types";
import { LoginFailuresDataSource } from "@/react/pages/audit/LoginFailuresDataSource";
import type { LoginFailureEvent } from "@/react/pages/audit/loginFailuresApi";

export function LoginFailureLogPage() {
  const gridRef = useRef<PageableGridContentHandle<LoginFailureEvent>>(null);
  const dataSource = useMemo(() => new LoginFailuresDataSource(), []);
  const [dateStart, setDateStart] = useState("");
  const [dateEnd, setDateEnd] = useState("");
  const [usernameLike, setUsernameLike] = useState("");

  const columnDefs = useMemo<ColDef<LoginFailureEvent>[]>(
    () => [
      { field: "id", headerName: "ID", sortable: true, flex: 0.5 },
      { field: "username", headerName: "사용자명", sortable: true, flex: 1 },
      { field: "remoteIp", headerName: "IP 주소", sortable: true, flex: 1 },
      { field: "failureType", headerName: "예외 유형", sortable: true, flex: 1.25 },
      { field: "message", headerName: "메시지", sortable: true, flex: 1.75 },
      { field: "userAgent", headerName: "User-Agent", sortable: true, flex: 2.5 },
      {
        field: "occurredAt",
        headerName: "시각",
        sortable: true,
        flex: 1.5,
        valueFormatter: (params) =>
          params.value ? new Date(params.value).toLocaleString() : "",
      },
    ],
    []
  );

  const handleRefresh = () => {
    gridRef.current?.refresh();
  };

  function setPreset(days: number) {
    const now = new Date();
    const end = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const start = new Date(end);
    start.setDate(start.getDate() - (days - 1));
    setDateStart(start.toISOString().slice(0, 10));
    setDateEnd(end.toISOString().slice(0, 10));
  }

  function setToday() {
    setPreset(1);
  }

  function set7days() {
    setPreset(7);
  }

  function set30days() {
    setPreset(30);
  }

  function set6Months() {
    const now = new Date();
    const start = new Date(now.getFullYear(), now.getMonth() - 6, now.getDate());
    const end = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    setDateStart(start.toISOString().slice(0, 10));
    setDateEnd(end.toISOString().slice(0, 10));
  }

  function setThisMonth() {
    const now = new Date();
    const start = new Date(now.getFullYear(), now.getMonth(), 1);
    const end = new Date(now.getFullYear(), now.getMonth() + 1, 0);
    setDateStart(start.toISOString().slice(0, 10));
    setDateEnd(end.toISOString().slice(0, 10));
  }

  function startOfDayLocalToIso(dateStr: string) {
    const [y = 0, m = 1, d = 1] = dateStr.split("-").map(Number);
    return new Date(y, m - 1, d, 0, 0, 0, 0).toISOString();
  }

  function endOfDayExclusiveLocalToIso(dateStr: string) {
    const [y = 0, m = 1, d = 1] = dateStr.split("-").map(Number);
    return new Date(y, m - 1, d + 1, 0, 0, 0, 0).toISOString();
  }

  const validRange = !dateStart || !dateEnd || dateStart <= dateEnd;

  const handleSearch = () => {
    if (!validRange) {
      return;
    }

    const filter: Record<string, string> = {};
    if (dateStart) {
      filter.from = startOfDayLocalToIso(dateStart);
    }
    if (dateEnd) {
      filter.to = endOfDayExclusiveLocalToIso(dateEnd);
    }
    if (usernameLike.trim()) {
      filter.usernameLike = usernameLike.trim();
    }
    dataSource.applyFilter(filter);
    gridRef.current?.refresh();
  };

  useEffect(() => {
    setPreset(7);
  }, []);

  return (
    <Stack spacing={2}>
      <Breadcrumbs separator="›">
        <Typography color="text.secondary">시스템관리</Typography>
        <Typography color="text.secondary">감사</Typography>
        <Typography color="text.primary">로그인 실패</Typography>
      </Breadcrumbs>

      <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <Typography variant="h5">로그인 실패 로그</Typography>
        <Stack direction="row" spacing={1}>
          <Button
            variant="text"
            startIcon={<RefreshOutlined />}
            onClick={handleRefresh}
          >
            새로고침
          </Button>
        </Stack>
      </Box>

      <Stack spacing={1}>
        <Stack direction={{ xs: "column", md: "row" }} spacing={1}>
          <TextField
            label="시작일(포함)"
            type="date"
            size="small"
            value={dateStart}
            onChange={(event) => setDateStart(event.target.value)}
            InputLabelProps={{ shrink: true }}
            error={!validRange}
            fullWidth
          />
          <TextField
            label="종료일(포함)"
            type="date"
            size="small"
            value={dateEnd}
            onChange={(event) => setDateEnd(event.target.value)}
            InputLabelProps={{ shrink: true }}
            error={!validRange}
            helperText={!validRange ? "시작일이 종료일보다 늦을 수 없습니다." : " "}
            fullWidth
          />
          <TextField
            label="아이디"
            size="small"
            value={usernameLike}
            onChange={(event) => setUsernameLike(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter") {
                handleSearch();
              }
            }}
            fullWidth
          />
        </Stack>
        <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 1 }}>
          <ButtonGroup size="small" variant="outlined">
            <Button onClick={setToday}>오늘</Button>
            <Button onClick={set7days}>7일</Button>
            <Button onClick={set30days}>30일</Button>
            <Button onClick={set6Months}>6개월</Button>
            <Button onClick={setThisMonth}>이번달</Button>
          </ButtonGroup>
          <Button
            variant="outlined"
            startIcon={<RefreshOutlined />}
            onClick={handleSearch}
            disabled={!validRange}
          >
            조회
          </Button>
        </Box>
      </Stack>

      <PageableGridContent<LoginFailureEvent>
        ref={gridRef}
        datasource={dataSource}
        columns={columnDefs}
      />
    </Stack>
  );
}
