// src/react/pages/admin/GroupsPage.tsx
import { useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  Alert,
  Box,
  Button,
  IconButton,
  Stack,
  Tooltip,
} from "@mui/material";
import {
  ChevronRight,
  DeleteOutlined,
  GroupAddOutlined,
  GroupOutlined,
} from "@mui/icons-material";
import type { ColDef, ICellRendererParams } from "ag-grid-community";
import { PageableGridContent } from "@/react/components/ag-grid";
import type { PageableGridContentHandle } from "@/react/components/ag-grid/types";
import type { GroupDto } from "@/react/pages/admin/datasource";
import { GroupsDataSource } from "@/react/pages/admin/datasource";
import { reactGroupsApi } from "@/react/pages/admin/groups/api";
import { GroupDialog } from "@/react/pages/admin/groups/GroupDialog";
import { PageToolbar } from "@/react/components/page/PageToolbar";
import { useConfirm, useToast } from "@/react/feedback";

export function GroupsPage() {
  const navigate = useNavigate();
  const confirm = useConfirm();
  const toast = useToast();
  const gridRef = useRef<PageableGridContentHandle<GroupDto>>(null);
  const dataSource = useMemo(() => new GroupsDataSource(), []);
  const [searchInput, setSearchInput] = useState("");
  const [searchError, setSearchError] = useState<string | null>(null);
  const [createOpen, setCreateOpen] = useState(false);

  const columnDefs = useMemo<ColDef<GroupDto>[]>(
    () => [
      {
        field: "name",
        headerName: "이름",
        filter: false,
        sortable: true,
        flex: 0.8,
        cellRenderer: (params: ICellRendererParams<GroupDto>) => (
          <Box
            component="button"
            type="button"
            aria-label={`${params.value} 상세보기`}
            onClick={() => navigate(`/admin/groups/${params.data?.groupId}`)}
            sx={{
              border: 0,
              p: 0,
              bgcolor: "transparent",
              color: "primary.main",
              cursor: "pointer",
              font: "inherit",
              textAlign: "left",
              "&:hover": { textDecoration: "underline" },
            }}
          >
            {params.value}
          </Box>
        ),
      },
      {
        field: "description",
        headerName: "설명",
        filter: false,
        sortable: false,
        flex: 1.2,
      },
      {
        field: "memberCount",
        headerName: "멤버",
        filter: false,
        sortable: false,
        flex: 0.4,
        cellStyle: { textAlign: "right" },
      },
      {
        field: "creationDate",
        headerName: "생성일",
        filter: false,
        sortable: true,
        type: "datetime",
        flex: 0.8,
      },
      {
        field: "modifiedDate",
        headerName: "수정일",
        filter: false,
        sortable: true,
        type: "datetime",
        flex: 0.8,
      },
      {
        colId: "actions",
        headerName: "작업",
        filter: false,
        sortable: false,
        width: 112,
        minWidth: 112,
        maxWidth: 112,
        pinned: "right",
        cellStyle: { display: "flex", alignItems: "center", justifyContent: "center" },
        cellRenderer: (params: ICellRendererParams<GroupDto>) => (
          <Box sx={{ display: "flex", gap: 0.5, alignItems: "center", height: "100%" }}>
            <Tooltip title="멤버 관리">
              <IconButton
                size="small"
                aria-label="멤버 관리"
                onClick={() =>
                  params.data?.groupId &&
                  navigate(`/admin/groups/${params.data.groupId}`, { state: { openMembers: true } })
                }
              >
                <GroupOutlined fontSize="small" />
              </IconButton>
            </Tooltip>
            <Tooltip title="삭제">
              <IconButton
                size="small"
                color="error"
                aria-label="삭제"
                onClick={() => params.data && void handleDeleteGroup(params.data)}
              >
                <DeleteOutlined fontSize="small" />
              </IconButton>
            </Tooltip>
            <Tooltip title="상세보기">
              <IconButton
                size="small"
                aria-label="상세보기"
                onClick={() => navigate(`/admin/groups/${params.data?.groupId}`)}
              >
                <ChevronRight fontSize="small" />
              </IconButton>
            </Tooltip>
          </Box>
        ),
      },
    ],
    [navigate]
  );

  const handleSearch = () => {
    setSearchError(null);
    dataSource.applyFilter(
      searchInput.trim()
        ? { q: searchInput.trim(), in: "name,description" }
        : {}
    );
    gridRef.current?.refresh();
  };

  const handleRefresh = () => {
    setSearchError(null);
    gridRef.current?.refresh();
  };

  async function handleDeleteGroup(group: GroupDto) {
    const ok = await confirm({
      title: "그룹 삭제",
      message: `${group.name} 그룹을 삭제하시겠습니까?`,
      okText: "삭제",
      cancelText: "취소",
    });
    if (!ok) {
      return;
    }

    try {
      await reactGroupsApi.deleteGroup(group.groupId);
      toast.success("그룹이 삭제되었습니다.");
      gridRef.current?.refresh();
    } catch {
      toast.error("그룹 삭제에 실패했습니다.");
    }
  }

  return (
    <Stack spacing={0.5}>
      <PageToolbar
        divider={false}
        breadcrumbs={["시스템관리", "보안관리", "그룹"]}
        label="그룹을 검색하고 멤버십과 역할을 관리합니다."
        onRefresh={handleRefresh}
        searchPlaceholder="이름, 설명 검색"
        searchValue={searchInput}
        onSearchValueChange={setSearchInput}
        onSearch={handleSearch}
        actions={
          <Tooltip title="그룹 생성">
            <IconButton size="small" aria-label="그룹 생성" onClick={() => setCreateOpen(true)}>
              <GroupAddOutlined fontSize="small" />
            </IconButton>
          </Tooltip>
        }
      />

      {searchError && <Alert severity="error">{searchError}</Alert>}

      <PageableGridContent<GroupDto>
        ref={gridRef}
        datasource={dataSource}
        columns={columnDefs}
      />
      <GroupDialog
        open={createOpen}
        onClose={() => setCreateOpen(false)}
        onCreated={() => gridRef.current?.refresh()}
      />
    </Stack>
  );
}

// src/views/mgmt/security/GroupsPage.vue
<template>
    <v-breadcrumbs class="pa-0" :items="['시스템관리', '보안관리', '그룹']" density="compact"></v-breadcrumbs>
    <PageToolbar title="Groups" class="ba-0 bg-white" @refresh="refresh" @create="onCreate" :closeable="false"
        :divider="false" :items="[
            { icon:'mdi-account-multiple-plus', tooltip:'그룹 생성', text: 'Create Group', variant: 'text', event: 'create', color: 'blue', },
            { icon: 'mdi-refresh', event: 'refresh', }]" ></PageToolbar>
    <v-row>
        <v-col cols="12" md="12">
            <PageableGridContent @filter-actived="onPageableGridFilterActived" ref="pageableGridContentRef"
                :datasource="dataStore" :columns="columnDefs">
            </PageableGridContent>
        </v-col>
    </v-row>
    <GroupDialog v-model="groupDialog.visible" :groupId="groupDialog.groupId" @close="groupDialog.visible = false"
        @updated="refresh"></GroupDialog>
    <MembershipDialog v-model="groupMembershipDialog.visible" :groupId="groupMembershipDialog.groupId" @updated="refresh" @close="groupMembershipDialog.visible=false"></MembershipDialog>        
</template>
<script setup lang="ts">
import PageableGridContent from '@/components/ag-grid/PageableGridContent.vue';
import { computed, onMounted, ref } from 'vue';
import type { ColDef } from 'ag-grid-community';
import { usePageableGroupsStore } from '@/stores/studio/groups.store';
import PageToolbar from '@/components/buttons/PageToolbar.vue';
import ActionCellRenderer from '@/components/ag-grid/renderer/ActionCellRenderer.vue';
import GroupDialog from "./GroupDialog.vue";
import MembershipDialog from './GroupMembershipDialog.vue';
import { useRouter } from 'vue-router';
import { useToast } from '@/plugins/toast';
import { useConfirm } from '@/plugins/confirm';
// grid 
const dataStore = usePageableGroupsStore();
const router = useRouter()
const gridData = ref<any[]>();
const loader = ref(false);
const confirm = useConfirm();
const toast = useToast();
// define grid columns
async function onAction({ action, row }: { action: string; row: any }) {
    if (action === 'view') {
        router.push({ name: 'GroupDetails', params: { groupId: row.groupId } })
    } else if (action === 'membership'){
        groupMembershipDialog.value.groupId = row.groupId;
        groupMembershipDialog.value.visible = true;
    } else if (action === 'delete') {
        const ok = await confirm({
            title: '확인',
            message: `'${row.name}' 그룹을 삭제할까요?`,
            okText: '확인',
            cancelText: '취소',
            color: 'primary',
        });
        if (!ok) return;
        toast.success(`'${row.name}' 가 삭제되었습니다.`);
    }
}
const columnActions = [
    {
        label: '삭제',
        variant: 'outlined',
        prependIcon: 'mdi-delete',
        color: 'red',
        event: 'delete',
        visible: true,
        tooltip: '그룹을 삭제합니다.'
    },
    {
        label: '멤버',
        color: 'blue',
        variant: 'outlined',
        prependIcon: 'mdi-account-multiple',
        event: 'membership',
        visible: true,
        tooltip: '그룹 구성원을 관리합니다.',
        disabled: false,
    },
    {
        label: '상세보기',
        icon: 'mdi-chevron-right',
        event: 'view',
        visible: true,
        disabled: false,
    }
];
const columnDefs: ColDef[] = [
    { field: 'name', headerName: '이름', filter: false, sortable: true, type: "hyperlinks", flex: 1 , cellRendererParams: {
      mode: 'router',
      to: (d: any) => ({ name: 'GroupDetails', params: { groupId: d.groupId } }),
      router: router,
    }},
    { field: 'description', headerName: '설명', filter: false, sortable: false, type: 'string', flex: 2, },
    { field: 'memberCount', headerName: '맴버', filter: false, sortable: false, type: "number", flex: .25 },
    { field: 'creationDate', headerName: '생성일', filter: false, type: 'datetime', flex: 1 },
    { field: 'modifiedDate', headerName: '수정일', filter: false, type: 'datetime', flex: 1 },
    { colId: 'actions', headerName: '', filter: false, sortable: false, flex: 1.2, cellRenderer: ActionCellRenderer, cellRendererParams: { actions: columnActions, onAction } },
];
const pageableGridContentRef = ref<InstanceType<typeof PageableGridContent> | null>(null);
const filtersActive = ref(false);
function onPageableGridFilterActived(event: any) {
    filtersActive.value = event;
}
const refresh = () => {
    pageableGridContentRef.value?.refresh();
}
const onClearFilters = () => {
    pageableGridContentRef.value?.clearFilters();
};

const groupDialog = ref({
    visible: false,
    groupId: 0,
});

const groupMembershipDialog = ref({
    visible: false,
    groupId: 0,
});

const onCreate = () => {
    groupDialog.value.visible = true;
};

const selectedRows = computed(() => pageableGridContentRef.value?.selectedRows() || []);

onMounted(() => {
});

</script>
